### ISSUE TITLE
Sudden rotation occurs during mapping

### ISSUE THREAD

**Issue by Oofs** [RobustFieldAutonomyLab/LeGO-LOAM#10]
Hi Shan,

I  have tested your algorithm with my own datasets (VLP-16, no imu data), in dataset1, map is perfect with little drift (pic1, pic2). But in dataset2, it occurs a sudden rotation in the built map(pic3, pic4). 
My lidar is mounted on the surface of handcart (1m height) which moves smoothly.
Do you have any idea about this ? Or do you have any suggestions about which parameters should be adjusted accordingly ?
![1](https://user-images.githubusercontent.com/16382039/44144101-cd0c1a64-a0b8-11e8-9d47-39395cd556b3.png)
![2](https://user-images.githubusercontent.com/16382039/44144109-d1f1db7c-a0b8-11e8-9bd6-aefac3f7e0a1.png)
![3](https://user-images.githubusercontent.com/16382039/44144182-15fedf9a-a0b9-11e8-8622-bf07f466b105.png)
![4](https://user-images.githubusercontent.com/16382039/44144188-1a8c182a-a0b9-11e8-978e-827403886b65.png)

Yours,
Claude

**Comment by TixiaoShan** [comment]
What's the rotation rate of your VLP-16? It looks like it's rotating at 5Hz.

**Comment by deliangye** [comment]
I run into a similar issue when I test with gates_oscillating_motion.bag from JI Zhang.

**Comment by TixiaoShan** [comment]
@deliangye 
Yeah, I do remember people mention that the map would diverge even when the original LOAM is used.

**Comment by Oofs** [comment]
Thanks for your  replies ! @TixiaoShan @deliangye 

My VLP-16 rate is 10hz(600RPM). I guess maybe it's the problem of the way recording bag file.
I use `roslaunch velodyne_pointcloud VLP16_points.launch pcap:="/.../"` to play the data while another thread is recording the pointcloud to the bag file `rosbag record /velodyne_points`.

How do you guys convert pcap to bag ?

**Comment by TixiaoShan** [comment]
@Oofs 
When I run that package, there is a /velodyne_points topic I can subscribe to. I can use it for online mapping or recording a bag.

**Comment by Oofs** [comment]
@TixiaoShan 
Thats exactly the way i did. But I found that when i use velodyne_pointcloud to play the .pcap files, it appears that the point_cloud is not read correctly and incomplete (some circular sector shadow in the pointcloud).
But when i use veloview to read pcap file, the pointcloud seems complete.
Have you ever experienced this ?
![shadow](https://user-images.githubusercontent.com/16382039/44183363-46573f00-a13d-11e8-8f80-95c6eb886c59.png)
![veloview](https://user-images.githubusercontent.com/16382039/44183364-48b99900-a13d-11e8-84a1-c10a52169240.png)

**Comment by Oofs** [comment]
@TixiaoShan 
well, seems like a known bug when using velodyne_pointcloud to read pcap files.
Thanks anyway :)  https://github.com/ros-drivers/velodyne/issues/116

**Comment by TixiaoShan** [comment]
Close the topic for now. Feel free to re-open with new data.
