### ISSUE TITLE
how to check the loopclosure?

### ISSUE THREAD

**Issue by 14212094** [RobustFieldAutonomyLab/LeGO-LOAM#101]
Thank you for you great job
I try the lego-loam with my dataset,some problem happen in the localization,as the picture below. Maybe the loopclosure was not detected,how can i solve this? Thank you!!!
![____________ 2019-07-01 17_18_11](https://user-images.githubusercontent.com/38451498/60809144-8a6f8a00-a1bc-11e9-92cb-3235dbb3b968.png)

**Comment by 14212094** [comment]
Because of the problem of calibration,I perform this without IMU data.

**Comment by hg12138** [comment]
hi，have you solved it？I encountered a similar problem.When returning to the initial position, there is a ghost phenomenon
