### ISSUE TITLE
always drift z direction

### ISSUE THREAD

**Issue by sujiongming** [RobustFieldAutonomyLab/LeGO-LOAM#102]
I have tried some ways to solve this problem, but it doesn't works:

- extern const bool loopClosureEnableFlag = true;(in utility.h)

- if (abs(angle - sensorMountAngle) <= 20,40) (in imageProjection.cpp)

Is there any way to solve it?

**Comment by mutou-2015** [comment]
hello, I also met this question.
![use_imu](https://user-images.githubusercontent.com/46196703/61193558-a9a37580-a6ee-11e9-89cc-ab6e41a27d10.png)

**Comment by PenghangF** [comment]
I also met this question，have u resolved this finally?
