### ISSUE TITLE
rviz process died after doing roslaunch 

### ISSUE THREAD

**Issue by llu0120** [RobustFieldAutonomyLab/LeGO-LOAM#103]
Hi,
Do anyone know why the rviz died automatically after doing `roslaunch ` like below? 
![Selection_005](https://user-images.githubusercontent.com/41609738/61033448-1caea280-a3f6-11e9-99ae-1efb9f9e1098.png)
Thank you!

**Comment by geoffzhang** [comment]
@llu0120 @TixiaoShan I have the same question, do you  know how to sloved it now?

**Comment by TixiaoShan** [comment]
I recommend creating a new rviz config file instead of using the one from the repository. Feel free to reopen the issue if the problem persists.
