### ISSUE TITLE
When roslaunch , LeGO-LOAM Crashing

### ISSUE THREAD

**Issue by wings0728** [RobustFieldAutonomyLab/LeGO-LOAM#109]
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jason-XPS-15-9560:38201/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    base_link_to_camera (tf/static_transform_publisher)
    camera_init_to_map (tf/static_transform_publisher)
    featureAssociation (lego_loam/featureAssociation)
    imageProjection (lego_loam/imageProjection)
    mapOptmization (lego_loam/mapOptmization)
    rviz (rviz/rviz)
    transformFusion (lego_loam/transformFusion)

auto-starting new master
process[master]: started with pid [1258]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 75a42902-b376-11e9-985d-9cb6d0ec358b
process[rosout-1]: started with pid [1274]
started core service [/rosout]
process[rviz-2]: started with pid [1284]
process[camera_init_to_map-3]: started with pid [1299]
process[base_link_to_camera-4]: started with pid [1300]
process[imageProjection-5]: started with pid [1312]
process[featureAssociation-6]: started with pid [1329]
process[mapOptmization-7]: started with pid [1338]
process[transformFusion-8]: started with pid [1339]
[ INFO] [1564565697.977481930]: ----> Transform Fusion Started.
[ INFO] [1564565698.005028948]: ----> Feature Association Started.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[ INFO] [1564565698.149528564]: ----> Image Projection Started.
[mapOptmization-7] process has died [pid 1338, exit code -11, cmd /home/jason/catkin_ws/devel/lib/lego_loam/mapOptmization __name:=mapOptmization __log:=/home/jason/.ros/log/75a42902-b376-11e9-985d-9cb6d0ec358b/mapOptmization-7.log].
log file: /home/jason/.ros/log/75a42902-b376-11e9-985d-9cb6d0ec358b/mapOptmization-7*.log

**Comment by facontidavide** [comment]
Does this happen everytime on your computer or sporadically? Can it be reproduced with a rosbag?

Without further information and a way to reproduce this, if is impossible to fix the issue.
