### ISSUE TITLE
About the rate factor of rosbag play 

### ISSUE THREAD

**Issue by HViktorTsoi** [RobustFieldAutonomyLab/LeGO-LOAM#112]
Is there a implied condition that the rate(factor) of `rosbag play` must be 1? 

When I tried to speed up the running time by using a rosbag play rate higer than 1 (e.g. -r=20), there is serious bias in the results, as shown in following figures.

![image](https://user-images.githubusercontent.com/25725035/62367126-496c5a80-b55b-11e9-9b37-ba8ca5f5cf4b.png)
_fig.1. rosbag play -r=1 (normal)_

![image](https://user-images.githubusercontent.com/25725035/62367218-8a646f00-b55b-11e9-9703-d6a60d967a5d.png)
_fig.2. rosbag play -r=20  (wrong)_

![image](https://user-images.githubusercontent.com/25725035/62367560-a288be00-b55c-11e9-95a7-3ece223af81d.png)
_fig.3. rosbag play -r=100  (wrong)_

So is there a implied require that the rate of `rosbag play` should be 1?  Or is there a way to increase the play rate without hurting the performance? Thanks a lot.

**Comment by facontidavide** [comment]
Short answer : yes, use rate 1

Long answer: not necessarily 1, but not 20 for sure.

The software is implemented with 3 individual nodes. You need to allow enough time to each node to perform its computation or some measurements will be "skipped".

This is strongly related to issue #107

**Comment by Scrumantic** [comment]
I've processed forestry acquired bags at 10x rate without problems. Although for my solution I limit the VLP16 range to 50 meters.

**Comment by facontidavide** [comment]
Hi. 

I have solved this issue... doing a heavy refactoring of the code. Please refer to the comment in #107
