### ISSUE TITLE
Gtsam optimization did not work

### ISSUE THREAD

**Issue by mutou-2015** [RobustFieldAutonomyLab/LeGO-LOAM#113]
@TixiaoShan ,
hi Shan,
I found Gtsam optimization did not work when I test your code with Stevens-VLP16-Dataset.
The value of transformAftMapped was printed as follow,
![222](https://user-images.githubusercontent.com/46196703/62446891-8a9c7e80-b796-11e9-9e5b-f34974788656.png)
![111](https://user-images.githubusercontent.com/46196703/62446907-92f4b980-b796-11e9-9328-0d12f9a6056a.png)
There is no difference between the pre-optimization and the optimized values.Can you explain my doubts？Thanks.

**Comment by jxhstrive** [comment]
@mutou-2015 
Hi,
I also met the same problem. The optimized values were not changed. I have set loopClosureEnableFlag the value is true. Has the problem been solved? Thank you very much for your communication and discussion.
