### ISSUE TITLE
QUESTION to both maintainers and users: is IMU any useful?

### ISSUE THREAD

**Issue by facontidavide** [RobustFieldAutonomyLab/LeGO-LOAM#127]
In my experience, adding the IMU data does more arm than good.

Does anyone confirm that using this software with an IMU does actually improve performance?

**Comment by TixiaoShan** [comment]
Yes, it is very helpful. I have observed that many testing cases will fail without IMU data - when the robot makes aggressive roll, pitch and yaw motions.

**Comment by facontidavide** [comment]
Thnaks. I was trying to decide if the entire part related to IMU could be refactored in my fork or if it made more sense just to remove it.
