### ISSUE TITLE
The problem about findStartEndAngle()

### ISSUE THREAD

**Issue by yycchen** [RobustFieldAutonomyLab/LeGO-LOAM#133]
Hi!
I wonder why the code of endOrientation in findStartEndAngle is -2 rather than -1?

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/master/LeGO-LOAM/src/imageProjection.cpp#L188
`segMsg.endOrientation   = -atan2(laserCloudIn->points[laserCloudIn->points.size() - 1].y,
laserCloudIn->points[laserCloudIn->points.size() - 2].x) + 2 * M_PI;`

**Comment by TixiaoShan** [comment]
@yycchen 
That was a typo. I forgot to correct it. Thanks for pointing it out.

**Comment by yycchen** [comment]
OK!
@TixiaoShan Thanks for your help.
