### ISSUE TITLE
ouster lidar setting

### ISSUE THREAD

**Issue by louis960126** [RobustFieldAutonomyLab/LeGO-LOAM#134]
Hi, 
I have an ouster 64 channel lidar. I already change the topic name to ouster lidar's topic name and change the utility.h to os1-64, but there is still some problem to run LeGO-LOAM. Do i need to change other settings?

Thank you!

**Comment by louis960126** [comment]
For frame [base_link]: No transform to fixed frame [map]. TF error: [Lookup would require extrapolation into the past. Requested time 1464.161704880 but the earliest data is at time 1571715599.269487703, when looking up transform from frame [base_link] to frame [map]]

**Comment by louis960126** [comment]
velodyne lidar is ok

**Comment by louis960126** [comment]
![image](https://user-images.githubusercontent.com/43161306/67258157-e3d89c00-f4c1-11e9-818e-6b17fae25e3a.png)
![image](https://user-images.githubusercontent.com/43161306/67258171-f2bf4e80-f4c1-11e9-863c-c8030b4d246b.png)

**Comment by TixiaoShan** [comment]
Try to comment this line.
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/744254789c91ebe4851b4678be2c9f97e2f56c27/LeGO-LOAM/src/imageProjection.cpp#L159

**Comment by LeisureLei** [comment]
I meet the same problem.I play the bag file and I get nothing in rviz.There is alse a error in rviz :+1: For frame [base_link]: No transform to fixed frame [map]. TF error: [Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.]
I also uncomment line 159 and catkin_make agian.Nothin changes.
How can I fix this problem?

**Comment by YiChenCityU** [comment]
> I meet the same problem.I play the bag file and I get nothing in rviz.There is alse a error in rviz  For frame [base_link]: No transform to fixed frame [map]. TF error: [Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.]
> I also uncomment line 159 and catkin_make agian.Nothin changes.
> How can I fix this problem?

Hi, have you solved this problem?

**Comment by YiChenCityU** [comment]
> Hi,
> I have an ouster 64 channel lidar. I already change the topic name to ouster lidar's topic name and change the utility.h to os1-64, but there is still some problem to run LeGO-LOAM. Do i need to change other settings?
> 
> Thank you!

Hi, have you solved this problem?

**Comment by Oyssster** [comment]
Hi,is there anyone solved this problem?

**Comment by shahaizi0** [comment]
你好，请问有人解决了这个问题吗

**Comment by orange-cr** [comment]
I run the park.bag provided by lio-sam and meet the same problem. I solved this problem by:
(1)in run.launch 
the parameter "/use_sim_time" is set to "true"
(2)rosbag play park.bag --clock
(3)uncomment this line in imageProjection.cpp at line 166
cloudHeader.stamp = ros::Time::now(); // Ouster lidar users may need to uncomment this line
