### ISSUE TITLE
imageProjection died

### ISSUE THREAD

**Issue by he-guo** [RobustFieldAutonomyLab/LeGO-LOAM#135]
I have encountered the following problem, imageprojection died when doing real-time mapping.can you help me?thanks
![lego-loam error](https://user-images.githubusercontent.com/54622758/67353502-4cd51800-f585-11e9-8278-56b80092e66a.png)

**Comment by heroacool** [comment]
plz show the log

**Comment by TixiaoShan** [comment]
Close the issue due to a lack of details.
