### ISSUE TITLE
Loop Closure Understanding

### ISSUE THREAD

**Issue by Chenweng1** [RobustFieldAutonomyLab/LeGO-LOAM#137]
Hi @TixiaoShan ,

Can you please tell me what is loop closure and how to activate the loop closure ? Also is there any way that I can save the generated map into pcd file ?If so, can you tell me how to do that?

Thanks 

Weng

**Comment by TixiaoShan** [comment]
Hi @Chenweng1 
This link will probably help you understand [loop closure](https://www.google.com/search?q=what+is+loop+closure&oq=what+is+loop+closure&aqs=chrome..69i57j0l5.5393j1j7&sourceid=chrome&ie=UTF-8).

The map saving function is already implemented.
