### ISSUE TITLE
Final Map Size

### ISSUE THREAD

**Issue by Dinatorehanova** [RobustFieldAutonomyLab/LeGO-LOAM#138]
Hi @TixiaoShan 

The final map in the form of .pcd generated by ctrl+c is very short in size and also it misses most of the features. Anyway to update it or its quality/size ?

Thanks

**Comment by TixiaoShan** [comment]
Yes, you can change some parameters like ```extern const float globalMapVisualizationSearchRadius = 500.0;``` to increase visualization range. Also, you can change [downSizeFilter](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/744254789c91ebe4851b4678be2c9f97e2f56c27/LeGO-LOAM/src/mapOptmization.cpp#L254)() resolution to get a finer map.
