### ISSUE TITLE
Question about the attitude of IMU relative to lidar

### ISSUE THREAD

**Issue by carleft** [RobustFieldAutonomyLab/LeGO-LOAM#140]
Hi Author!

I notice that 

> If you are using your lidar with an IMU, make sure your IMU is aligned properly with the lidar.

If Ｍy IMU is perpendicular to the Lidar, Can I adjust the attitude of IMU relative to lidar by publishing tf messages in the program? And How to do this ?

Thanks advance!

**Comment by TixiaoShan** [comment]
I think a transformed IMU should be enough, but I am not 100%. You can find more discussions on loam_velodyne.

https://github.com/laboshinl/loam_velodyne/issues/82
