### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by shaoxiaoyang** [RobustFieldAutonomyLab/LeGO-LOAM#142]
When I am running the "roslaunch lego_loam run.launch " in the terminal, it occur like this:
`process[rviz-1]: started with pid [11792]
process[camera_init_to_map-2]: started with pid [11793]
process[base_link_to_camera-3]: started with pid [11794]
process[imageProjection-4]: started with pid [11802]
process[featureAssociation-5]: started with pid [11818]
process[mapOptmization-6]: started with pid [11833]
process[transformFusion-7]: started with pid [11846]
[ INFO] [1574663130.415820702]: ----> Image Projection Started.
[ INFO] [1574663130.416681751]: ----> Feature Association Started.
[ INFO] [1574663130.434953265]: ----> Transform Fusion Started.

[mapOptmization-6] process has died [pid 11833, exit code -11, cmd /home/lilian/catkin_ws/devel/lib/lego_loam/mapOptmization __name:=mapOptmization __log:=/home/lilian/.ros/log/5a540d8e-0f4c-11ea-817a-c400ad22140a/mapOptmization-6.log].
log file: /home/lilian/.ros/log/5a540d8e-0f4c-11ea-817a-c400ad22140a/mapOptmization-6*.log
`
Who can tell the reason of this problem.

**Comment by TixiaoShan** [comment]
You must use the GTSAM specified in the readme file.
