### ISSUE TITLE
Problem about gtsam update & resize  in mapOptimization.cpp

### ISSUE THREAD

**Issue by heroacool** [RobustFieldAutonomyLab/LeGO-LOAM#145]
![image](https://user-images.githubusercontent.com/5468049/70018515-56f52800-15c1-11ea-80b7-2d8382063839.png)

Hi @TixiaoShan , when reading the mapOptimization.cpp, I am confusion with the gtsam update operation. What's the purpose of isam->update(), and why need to gtSAMgraph.resize(0) ?

It seems to reset the pose graph instance. If so,  it may not take the most advantage of gtsam. 

I try to comment these 3 lines, it will lead to error "key already exists". 

![image](https://user-images.githubusercontent.com/5468049/70018984-c7e90f80-15c2-11ea-8bec-7b8d675b8866.png)

So could you please explain the operation?
Great appreciation to your response.

**Comment by TixiaoShan** [comment]
Hi @heroacool 
I think that's the way to use isam2 in GTSAM, it clears the values for next optimization. One example can be found here. https://github.com/devbharat/gtsam/blob/master/examples/VisualISAM2Example.cpp

**Comment by heroacool** [comment]
> Hi @heroacool
> I think that's the way to use isam2 in GTSAM, it clears the values for next optimization. One example can be found here. https://github.com/devbharat/gtsam/blob/master/examples/VisualISAM2Example.cpp

Got it. Thanks !
