### ISSUE TITLE
error using ros-melodic

### ISSUE THREAD

**Issue by sam6134** [RobustFieldAutonomyLab/LeGO-LOAM#147]
Since the package is only tested on ros-kinetic and indigo , I have tried running this on ros-melodic since I have Ubuntu 18.04 . I am getting the map-Optimization error which is due to wrong version of gtsam , could please suggest which version to use for this case.
I am currently using the version you specified in the readme file.

**Comment by TixiaoShan** [comment]
Hi @sam6134 
I just tested the package Ubuntu 18.04 ROS Melodic and didn't find any problem. Have you tried another version of the gtsam?
