### ISSUE TITLE
A problem in function findCorrespondingSurfFeatures

### ISSUE THREAD

**Issue by xpchuan** [RobustFieldAutonomyLab/LeGO-LOAM#148]
at line 1160 in featureAssociation.cpp
`int j = closestPointInd + 1; j < surfPointsFlatNum; j++)`
why use `surfPointsFlatNum` instead of `laserCloudSurfLastNum`?

**Comment by xpchuan** [comment]
I saw a closed issue for this problem, but the newest code still has this problem

**Comment by TixiaoShan** [comment]
I think it should use ```laserCloudSurfLastNum```. Since ```surfPointsFlatNum``` is close to ```laserCloudSurfLastNum``` between two frames, I don't think there will be much observable difference.
