### ISSUE TITLE
Drift in z direction

### ISSUE THREAD

**Issue by Oofs** [RobustFieldAutonomyLab/LeGO-LOAM#15]
Hi Shan,

Thanks for your great job! However, I got some results which are not as good as yours in paper. Currently, I'm using VLP-16+imu to build the map in our campus, lidar is mounted at around 1.2m hight with imu attached to its top.  In some situations LeGO-LOAM suffers significant drift in z direction (ex. ~7 meters  after traveling around 400m), which didn't happen in x and y direction(x forward, y left, z up). 

I have tried to change  threshold in  **if (abs(angle - sensorMountAngle) <= 10)** to 1,5,15,20 but got no good result. 

I have also tried to change the map optimization update frequency in utility.h **extern const double mappingProcessInterval = 0.1**, but no luck.

Do you have any idea about this ?  Could you take a look at my bag file ? 

Looking forward to your reply.

Claude

bird view
![birdview](https://user-images.githubusercontent.com/16382039/44967410-b3f3cf80-af73-11e8-9638-ec9cdc8bc0d1.png)
z drift
![drift_z](https://user-images.githubusercontent.com/16382039/44967417-bb1add80-af73-11e8-9918-42972562807a.png)
path
![drift_z_path](https://user-images.githubusercontent.com/16382039/44967419-beae6480-af73-11e8-8b53-deadc77c3b78.png)
bag link
https://drive.google.com/file/d/1LFKV-jA1yjSHvUUCYCarzFO2UQdPD_0_/view?usp=sharing

**Comment by TixiaoShan** [comment]
I encounter z-drift too using your bag. One possible cause is that the vibration of lidar is very bad when you record the data, this will cause serious point cloud distortion. You can try enable the loop closure flag `loopClosureEnableFlag`. and also adjust  `historyKeyframeSearchRadius` depends on your drift.

**Comment by Oofs** [comment]
Thanks for your reply!
I had considered the vibration as a problem and changed a soft wheel of my robot (the old wheel is really rough). But  it seems that the vibration still exist. I'm planning to try this again when our new 4-wheels-robots is ready.
I have also tried the loop closure function to reduce the drift, yes the drift can be reduced but the map is not quiet accurate in some area as it try to find a global optimization of pose graph.
Do you think augmenter the frequency of  `scan2MapOptimization()` will reduce drift ?

**Comment by TixiaoShan** [comment]
Hi @Oofs , the data of your bag look weird to me. Here are two images playing my bag (first) and your bag (second). What is the configuration of your Velodyne, how is it installed on your cart?

![rviz_screenshot_2018_09_08-15_45_42](https://user-images.githubusercontent.com/9648219/45258037-9ca35080-b37e-11e8-925c-a1f9984193b6.png)
![rviz_screenshot_2018_09_08-15_46_25](https://user-images.githubusercontent.com/9648219/45258038-9f05aa80-b37e-11e8-9fd0-4fde51cdb684.png)

**Comment by Oofs** [comment]
My velodyne is mounted horizontally, with 90 degrees offset in yaw angle(clockwise). I believe this is why the green arrow points forward.

**Comment by mbudris** [comment]
oofs have you fixed your issues?

**Comment by gkharish** [comment]
Hello, I am having similar problem. When I enable the loopclosure the drift has reduced significantly. But the effect of loopclosure is not repeatable. While running the same rosbag file, loopclosure fix the z drift in some runs but id doesn't always fix the z drift, moreover the resulting trajectory is bit different each time drift is not corrected. Could you please give some insights?
