### ISSUE TITLE
If I increase the frequency of imu, what should I adjust in program? 

### ISSUE THREAD

**Issue by carleft** [RobustFieldAutonomyLab/LeGO-LOAM#150]
There is a const int imuQueLength in the program, and It has a value of 200. If the frequency of my imu is 400Hz, Should I change it to 400 or more? 

Thanks in advance!

**Comment by TixiaoShan** [comment]
You don't need to change anything. The imu queue length is to store the imu data during one scan. So you only need to change it when your imu frequency is over 2000Hz. Just make sure ```imuQueLength > imu-frequency / lidar-frequency```

**Comment by carleft** [comment]
> You don't need to change anything. The imu queue length is to store the imu data during one scan. So you only need to change it when your imu frequency is over 2000Hz. Just make sure `imuQueLength > imu-frequency / lidar-freque

OK , Thanks a lot~
