### ISSUE TITLE
bad kitti dataset test result

### ISSUE THREAD

**Issue by xuwuzhou** [RobustFieldAutonomyLab/LeGO-LOAM#151]
![图片](https://user-images.githubusercontent.com/44218507/71437941-9fba7f80-272e-11ea-8b0e-c668e83d97b6.png)
the result of kitti00sequence with IMU is really bad,the result looks like no loop closure,have anybody met a similar problem?

**Comment by TixiaoShan** [comment]
Right now the implementation for point cloud projection only works for VLP-16 and HDL-32E. Project point cloud nonlinearly and correctly on the range image can help improve accuracy.

**Comment by zcg3648806** [comment]
If you are using your lidar with an IMU, make sure your IMU is aligned properly with the lidar.

**Comment by zcg3648806** [comment]
If you are using your lidar with an IMU, make sure your IMU is aligned properly with the lidar.

**Comment by zcg3648806** [comment]
If you are using your lidar with an IMU, make sure your IMU is aligned properly with the lidar.

**Comment by xuwuzhou** [comment]
> Right now the implementation for point cloud projection only works for VLP-16 and HDL-32E. Project point cloud nonlinearly and correctly on the range image can help improve accuracy.
Thanks for your reply!
Since the lidar of kitti data is HDL-64,the  point cloud projection part in the lego-loam should be changed,isn't it?

**Comment by xuwuzhou** [comment]
Thanks for your reply!
Since the lidar of Kitti data is HDL-64,the implementation for point cloud projection in lego-loam should be changed ,isn't it?

**Comment by xuwuzhou** [comment]
Thanks for your @TixiaoShan reply!
Since the lidar of Kitti data is HDL-64,the implementation for point cloud projection in lego-loam should be changed ,isn't it?

**Comment by xuwuzhou** [comment]
Thanks for your @zcg3648806 reply!
I tested with KITTI 00sequence with IMU,and I use the calibs.txt with kitti2bag to generate a rosbag,how can I check if the IMU is aligned with the lidar.

**Comment by xuwuzhou** [comment]
@TixiaoShan Hi
Do you mean this issue,In fact I have changed the code as the issue say,and the result is not good as mentioned.
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/12#issuecomment-414406582

**Comment by TixiaoShan** [comment]
My comment on #12 is wrong. I thought the lidar beam of HDL-64 was distributed linearly, in fact, it's not. So a customized range image projection implementation needs to be done.

**Comment by xuwuzhou** [comment]
@TixiaoShan Thanks for your reply!
So what should I do to modify the code,generate a new code part to implement the range image projection?

**Comment by TixiaoShan** [comment]
@xuwuzhou 
You can change code in ```projectPointCloud()``` to implement it.

**Comment by zcg3648806** [comment]
@xuwuzhou in fact, i have the same problem. i don't know how to align the IMU to Lidar.If you don't mind, could you tell me how to do it？Thank you！

**Comment by zcg3648806** [comment]
@xuwuzhou Have you finished the new projection code with HDL-64e yet？ in fact,I don't quite understandbeam the distribution for this lidar(https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/tests/angles-calibrated.yaml)

**Comment by mengqingyu123** [comment]
Hello, I have just started to contact with lego-loam. How did you save the trajectory generated by lego-loam? Thank you very much!

**Comment by xuwuzhou** [comment]
@zcg3648806 Sorry ,I'm also troubled by this problem,would you tell me if you have any progress?Thank you!

**Comment by xuwuzhou** [comment]
@mengqingyu123 record the topic /aft_mapped_to_init

**Comment by mengqingyu123** [comment]
@xuwuzhou Thank you. I have recorded the message of /aft_mapped_to_init with rostopic echo, but its format cannot be compared with kitty's groundtruth. Have you used any tool to convert the data format? Thanks for your help!

**Comment by zcg3648806** [comment]
@xuwuzhou I think one of the reasons the imu of the kitii data set didn't perform well was that there was a distance between the imu and the lidar,it's my guess. But I don't know how to use Calibration file of kitti dataset(calib_velo_to_cam.txt)

**Comment by zcg3648806** [comment]
@mengqingyu123 you can try evo
https://michaelgrupp.github.io/evo/

**Comment by mengqingyu123** [comment]
@xuwuzhou Hello. Excuse me again. I recorded the /aft_mapped_to_init message in your way, as shown in figure 1 below, which is not available in the evo toolbox. I wrote a code in the source code to record the information related to pose, as shown in figure 2, but the data I finally got was only over 1000 lines, while the data in groundtruth was over 4000 lines. The evo toolbox required that the number of poses must be equal when drawing the kitti trajectory, so I still could not draw.

I have tried many methods, but all of them have failed. I hope you can tell me about your specific approach. Although you think the trajectory is not good enough, at least you can draw and analyze it, but I can't even draw it. Hope to get your reply, thank you!

/home/neousys/Pictures/trac.png
/home/neousys/Pictures/code.png

**Comment by mengqingyu123** [comment]
@xuwuzhou Hello. Excuse me again. I recorded the /aft_mapped_to_init message in your way, as shown in figure 1 below, which is not available in the evo toolbox. I wrote a code in the source code to record the information related to pose, as shown in figure 2, but the data I finally got was only over 1000 lines, while the data in groundtruth was over 4000 lines. The evo toolbox required that the number of poses must be equal when drawing the kitti trajectory, so I still could not draw.

I have tried many methods, but all of them have failed. I hope you can tell me about your specific approach. Although you think the trajectory is not good enough, at least you can draw and analyze it, but I can't even draw it. Hope to get your reply, thank you!
![trac](https://user-images.githubusercontent.com/37166419/71974931-c4921500-324d-11ea-8596-220bf53886e6.png)
![code](https://user-images.githubusercontent.com/37166419/71974943-cb208c80-324d-11ea-9405-b9bdbfa07362.png)

**Comment by zcg3648806** [comment]
@mengqingyu123  the number of poses can be not  equal when drawing the kitti trajectory with the evo tool,you can run:
evo_traj kitti KITTI_00_ORB.txt KITTI_00_SPTAM.txt --ref=KITTI_00_gt.txt -p --plot_mode=xz

**Comment by xuwuzhou** [comment]
@mengqingyu123 
Sorry,I haven't view the issue recently;
You can save the poses as tum format firstly,that's easy,then you can use evo transform the result as kitti format.

**Comment by xuwuzhou** [comment]
Hi, @zcg3648806 
Have you solved the problem?
Since the function projectPointcloud in imageProjection.cpp needed to be transformed;
I think the function laserCloudHandler in scanRegistration.cpp of A_LOAM can be meaningful for reference(Because the result of A_loam is good),but the problem haven't be solved up to now ,do you have any idea or progress?
Best wishes!

**Comment by zcg3648806** [comment]
@xuwuzhou No, I think I'm going to give up on testing the kitti dataset, and I now think the problem with the imu information is that it's too low in frequency. In the raw data of the kitti dataset, the frames of the imu and lidar are the same, but this is not reasonable. 10Hz is too low for an imu. In this algorithm, the imu data is used to correct the point cloud distortion and as the initial value of pose estimation. There is only one imu frame per radar frame, which should be the main reason for the poor performance of imu data. I think the secondary reason is that in the kitti data set, there is a certain distance between the imu installation location and the radar, which results in the imu information received by the algorithm cannot accurately represent the radar. 
In addition, I recently studied v-loam and found that the test performance on Kitti data set is also poor. I think the reason is the same as IMU, the image frame number of Kitti data set is the same as that of radar, and its frequency is too low. Normally, the image frame should be about 30Hz. To sum up, I think there are some problems in Kitti dataset itself.

**Comment by zcg3648806** [comment]
@xuwuzhou For the problem of radar point projection, I don't think it has much influence. I use the default configuration to run Kitti data set without IMU data, and the effect is very good.

**Comment by xuwuzhou** [comment]
@zcg3648806 
I'm very sorry for the late reply;
I have tested the data without IMU too,the result is really good;(But the sequence 01 have a large error )
Then,I must point out that the raw data and the sequence00-10 are not absolutely equal ,the difference is that the raw data is distorted,and the sequence00-10 is undistorted.The results get better partly because of this.
And ,the result without IMU lose some points,do you meet the same problem?

**Comment by abish-a** [comment]
Hi @xuwuzhou,
Can you share your repository which you implemented for KITTI dataset?

**Comment by abish-a** [comment]
Hi @xuwuzhou,
I am trying to run LeGO-LOAM on KITTI dataset, but I think I am missing some transformation as @TixiaoShan mentions in issue #12 . 
Do you have anything which I can refer to? Thanks in advance.

**Comment by zcg3648806** [comment]
@xuwuzhou
I'm very sorry for the late reply;
I don't know if there's a distortion difference between odometry and raw_data. But odometry doesn't have imu data. Besides, I want to ask you a little aside, do you have an algorithm for v-loam? I only found stevenliu216/demo_lidar on github, it works badly and it's not really v-loam in the strict sense.

**Comment by xuwuzhou** [comment]
@zcg3648806 Sorry,I don't have an algorithm for v-loam.
