### ISSUE TITLE
A problem in function calculateTransfromationSur

### ISSUE THREAD

**Issue by zhangwq1996** [RobustFieldAutonomyLab/LeGO-LOAM#152]
at line 1257 in featureAssociation.cpp
In  paper,we should estimate [tz,rx,ry] in step(1). But in code ,we get [ty,rx,rz] in step(1). why?

**Comment by TixiaoShan** [comment]
The ```[tz,rx,ry] ``` is in lidar frame. In LOAM, point cloud coordinates are transformed in ```487-489```. So the transformation ```[ty,rx,rz]``` in camera frame is equal to the transformation ```[tz,rx,ry] ``` in lidar frame.
