### ISSUE TITLE
question about the usage of the atan2()

### ISSUE THREAD

**Issue by zorosmith** [RobustFieldAutonomyLab/LeGO-LOAM#158]
Hello, I have question about the usage of the atan2() in the imageProjection.cpp. 
In the calculation of startOrientation, endOrientation and verticalAngle, you use atan2(y, x), however, in the calculation of horizonAngle, you use atan2(x, y). 
Is this designed this way, or just a mistake?

Any help will be appreciated!

**Comment by TixiaoShan** [comment]
It is designed that way, so the left of the image corresponds to the left of the point cloud.
