### ISSUE TITLE
About Kitti Experiment

### ISSUE THREAD

**Issue by vvaquero** [RobustFieldAutonomyLab/LeGO-LOAM#16]
Hi! congratulations for your great work. 

I was curious about the performance of the algorithm in Kitti. Apart from the speed over the Jetson, do you know how the performance would be affected if we use the full HDL64 pointcloud? 

I would love to do some more experiments over this dataset with the full pointcloud (as if real-time would not be a requirement). Maybe you could comment the parameters configuration that you use on the Kitti benchmark, and even share the results you obtained with your downsampled pointclouds? 

Thank you very much in advance. 

Best

**Comment by TixiaoShan** [comment]
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/12
