### ISSUE TITLE
How to integrate IMU and Point cloud Data of Ouster in the Algorithm?

### ISSUE THREAD

**Issue by adityarath302** [RobustFieldAutonomyLab/LeGO-LOAM#163]
I have been trying to use LeGo-LOAM for Ouster OS1-32 and was successful to get a 3D Point Cloud.
I want to know how to integrate the IMU with the algorithm.
Can you suggest me algorithms which give me a 3D point cloud by Ouster Lidar with IMU integration?

**Comment by TixiaoShan** [comment]
Hi @adityarath302 
Currently, LeGO-LOAM is not compatible with a 6-axis IMU because it needs roll, pitch, and yaw information to correct the pose. I think [lio-mapping](https://github.com/hyye/lio-mapping) works with Ouster lidar as it works with a 6-axis IMU.

**Comment by adityarath302** [comment]
Thank you so much @TixiaoShan

**Comment by L-Reichardt** [comment]
@TixiaoShan Great work on LegoLoam, I've been using it successfully with an OS1-64. Does this incompatibility with the 6-axis IMU still exist or was this ever changed?

**Comment by FalakFatima11** [comment]
I have been trying to use lego -LOAM for ouster os1 32 lidar to get 3d point cloud can you please give me an idea how to acheive it.

**Comment by MohammadAmmargk8497** [comment]
I have been getting only a single point cloud scan. How do I fix it
