### ISSUE TITLE
How to set the parameter named "groundScanInd"?

### ISSUE THREAD

**Issue by SubMishMar** [RobustFieldAutonomyLab/LeGO-LOAM#169]
Hi, I am using a VLP-32 for my research, I am not sure how to set the parameter "groundScanInd"? 
Will be glad if someone can help me here.

**Comment by TixiaoShan** [comment]
It's a rough number of scan lines that will cover the ground. For example, VLP-16 has 16 channels. Assume 8 channels can cover the ground. So the number is set to be 7 (starting from 0).
