### ISSUE TITLE
Any docs about transformAssociateToMap() ?

### ISSUE THREAD

**Issue by planckwu** [RobustFieldAutonomyLab/LeGO-LOAM#17]
Any docs or tips about the transformAssociateToMap algorithm?
I am going to  transform the keyframe pos to UTM coordinate maybe.

**Comment by TixiaoShan** [comment]
Hi @planckwu , sorry I don't have any insights in this function. I believe the best person who can answer this question is [Ji Zhang](http://www.frc.ri.cmu.edu/~jizhang03/).

**Comment by narutojxl** [comment]
Hi @planckwu,  I have the same question, did you slove you problem?
