### ISSUE TITLE
why "extern const string pointCloudTopic = "/velodyne_points";" is true?

### ISSUE THREAD

**Issue by qiaozhijian** [RobustFieldAutonomyLab/LeGO-LOAM#170]
why not output the error "multiple definition of `pointCloudTopic'", because pointCloudTopic is used in two cpps.

**Comment by YushengWHU** [comment]
Actually, I didn't quite understand you. This point cloud topic is reused in two cpps for sure, and you can change it to whatever topic you like, for my case, I just changed it to 
`subLaserCloud = nh.subscribe<sensor_msgs::PointCloud2>("/lidar0/points_raw", 1, &ImageProjection::cloudHandler, this);`
