### ISSUE TITLE
Some questions about loop closure detection

### ISSUE THREAD

**Issue by zcg3648806** [RobustFieldAutonomyLab/LeGO-LOAM#172]
extern const float surroundingKeyframeSearchRadius = 50.0; // key frame that is within n meters from current pose will be considerd for scan-to-map optimization (when loop closure disabled)
extern const int   surroundingKeyframeSearchNum = 50; // submap size (when loop closure enabled)
// history key frames (history submap for loop closure)
extern const float historyKeyframeSearchRadius = 7.0; // key frame that is within n meters from current pose will be considerd for loop closure
extern const int historyKeyframeSearchNum = 25; // 2n+1 number of hostory key frames will be fused into a submap for loop closure

If I want to make the loop closure detection as good as possible, which of the above parameters should be increased? and which should be reduced? Thank you!

**Comment by YushengWHU** [comment]
for my case, I just reduced the historyKeyframeSearchRadius from 7.0 to 5.0.
Sensor tested: Hesai 40 channel Lidar
Speed:             around 50km/h

**Comment by kissb2** [comment]
BTW fyi, 
I integrated the global loop detector (scan context) into the LeGO-LOAM pipeline
https://github.com/irapkaist/SC-LeGO-LOAM 
This ad-hook global loop detector works even large drift exist (e.g., https://www.youtube.com/watch?v=p-NsVs8GATA&feature=youtu.be&t=436)
and could enhance LeGO-LOAM's original radius search-based loop detection.

**Comment by zcg3648806** [comment]
@YushengWHU  @kissb2  Thank you for your reply！
