### ISSUE TITLE
how to use kitti datasets （vlp HDL-64E）for test?

### ISSUE THREAD

**Issue by shikeqin123** [RobustFieldAutonomyLab/LeGO-LOAM#175]
I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.

**Comment by bryantaoli** [comment]
> I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.

I also have this problem, can you deal with it？

**Comment by shikeqin123** [comment]
> > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> 
> I also have this problem, can you deal with it？

解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看

**Comment by bryantaoli** [comment]
> > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > 
> > 
> > I also have this problem, can you deal with it？
> 
> 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看

这说明kitti没办法跑lego_loam吗？

**Comment by shikeqin123** [comment]
> > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > 
> > 
> > I also have this problem, can you deal with it？
> 
> 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看



> > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > 
> > > 
> > > I also have this problem, can you deal with it？
> > 
> > 
> > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> 
> 这说明kitti没办法跑lego_loam吗？

论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句

**Comment by bryantaoli** [comment]
> > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > 
> > > 
> > > I also have this problem, can you deal with it？
> > 
> > 
> > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> 
> > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > 
> > > > 
> > > > I also have this problem, can you deal with it？
> > > 
> > > 
> > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > 
> > 
> > 这说明kitti没办法跑lego_loam吗？
> 
> 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句

ok，那这个开源也开的不是很准确啊

**Comment by shikeqin123** [comment]
> > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > 
> > > > 
> > > > I also have this problem, can you deal with it？
> > > 
> > > 
> > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > 
> > 
> > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > 
> > > > > 
> > > > > I also have this problem, can you deal with it？
> > > > 
> > > > 
> > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > 
> > > 
> > > 这说明kitti没办法跑lego_loam吗？
> > 
> > 
> > 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
> 
> ok，那这个开源也开的不是很准确啊

https://zhuanlan.zhihu.com/p/71731356 这个你看看

**Comment by shikeqin123** [comment]
> > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > 
> > > > 
> > > > I also have this problem, can you deal with it？
> > > 
> > > 
> > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > 
> > 
> > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > 
> > > > > 
> > > > > I also have this problem, can you deal with it？
> > > > 
> > > > 
> > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > 
> > > 
> > > 这说明kitti没办法跑lego_loam吗？
> > 
> > 
> > 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
> 
> ok，那这个开源也开的不是很准确啊

作者提供了他自己采的vlp16的数据集，需要翻墙下载

**Comment by bryantaoli** [comment]
> 作者提供了他自己采的vlp16的数据集，需要翻墙下载
老哥有链接吗

**Comment by shikeqin123** [comment]
> > 作者提供了他自己采的vlp16的数据集，需要翻墙下载
> > 老哥有链接吗

https://github.com/TixiaoShan/Stevens-VLP16-Dataset

**Comment by bryantaoli** [comment]
> > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > 
> > > > > 
> > > > > I also have this problem, can you deal with it？
> > > > 
> > > > 
> > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > 
> > > 
> > > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > > 
> > > > > > 
> > > > > > I also have this problem, can you deal with it？
> > > > > 
> > > > > 
> > > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > > 
> > > > 
> > > > 这说明kitti没办法跑lego_loam吗？
> > > 
> > > 
> > > 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
> > 
> > 
> > ok，那这个开源也开的不是很准确啊
> 
> 作者提供了他自己采的vlp16的数据集，需要翻墙下载

https://github.com/TixiaoShan/Stevens-VLP16-Dataset ，这个数据没啥用啊，只有激光，我想融合别的传感器还是得找别的数据

**Comment by shikeqin123** [comment]
> > > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > > 
> > > > > > 
> > > > > > I also have this problem, can you deal with it？
> > > > > 
> > > > > 
> > > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > > 
> > > > 
> > > > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > > > 
> > > > > > > 
> > > > > > > I also have this problem, can you deal with it？
> > > > > > 
> > > > > > 
> > > > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > > > 
> > > > > 
> > > > > 这说明kitti没办法跑lego_loam吗？
> > > > 
> > > > 
> > > > 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
> > > 
> > > 
> > > ok，那这个开源也开的不是很准确啊
> > 
> > 
> > 作者提供了他自己采的vlp16的数据集，需要翻墙下载
> 
> https://github.com/TixiaoShan/Stevens-VLP16-Dataset ，这个数据没啥用啊，只有激光，我想融合别的传感器还是得找别的数据

那只能找找其他数据集了。。或者自己采

**Comment by bryantaoli** [comment]
> > > > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > > > 
> > > > > > > 
> > > > > > > I also have this problem, can you deal with it？
> > > > > > 
> > > > > > 
> > > > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > > > 
> > > > > 
> > > > > > > > > I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I also have this problem, can you deal with it？
> > > > > > > 
> > > > > > > 
> > > > > > > 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
> > > > > > 
> > > > > > 
> > > > > > 这说明kitti没办法跑lego_loam吗？
> > > > > 
> > > > > 
> > > > > 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
> > > > 
> > > > 
> > > > ok，那这个开源也开的不是很准确啊
> > > 
> > > 
> > > 作者提供了他自己采的vlp16的数据集，需要翻墙下载
> > 
> > 
> > https://github.com/TixiaoShan/Stevens-VLP16-Dataset ，这个数据没啥用啊，只有激光，我想融合别的传感器还是得找别的数据
> 
> 那只能找找其他数据集了。。或者自己采

kitti激光这个也太差了吧，太惨了，还得自己修理

**Comment by shikeqin123** [comment]
我已放弃使用kitti来整这个算法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bryantaoli"<notifications@github.com&gt;; 
发送时间: 2020年5月1日(星期五) 中午11:20
收件人: "RobustFieldAutonomyLab/LeGO-LOAM"<LeGO-LOAM@noreply.github.com&gt;; 
抄送: "2509154582"<2509154582@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [RobustFieldAutonomyLab/LeGO-LOAM] how to use kitti datasets （vlp HDL-64E）for test? (#175)





         
I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
  
I also have this problem, can you deal with it？
  
解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
      
I have a problem to transform 64 lines pointclouds to 16 lines pointclouds.
  
I also have this problem, can you deal with it？
  
解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看
  
这说明kitti没办法跑lego_loam吗？
  
论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句
  
ok，那这个开源也开的不是很准确啊
  
作者提供了他自己采的vlp16的数据集，需要翻墙下载
  
https://github.com/TixiaoShan/Stevens-VLP16-Dataset ，这个数据没啥用啊，只有激光，我想融合别的传感器还是得找别的数据
  
那只能找找其他数据集了。。或者自己采
  
kitti激光这个也太差了吧，太惨了，还得自己修理

**Comment by bryantaoli** [comment]
> 我已放弃使用kitti来整这个算法
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bryantaoli"<notifications@github.com&gt;; 发送时间: 2020年5月1日(星期五) 中午11:20 收件人: "RobustFieldAutonomyLab/LeGO-LOAM"<LeGO-LOAM@noreply.github.com&gt;; 抄送: "2509154582"<2509154582@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [RobustFieldAutonomyLab/LeGO-LOAM] how to use kitti datasets （vlp HDL-64E）for test? (#175) I have a problem to transform 64 lines pointclouds to 16 lines pointclouds. I also have this problem, can you deal with it？ 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看 I have a problem to transform 64 lines pointclouds to 16 lines pointclouds. I also have this problem, can you deal with it？ 解决不了，kitti保存点云的方式是无序的，并不是一线一线存储，你可以算算单个点云的水平角和垂直角来看看 这说明kitti没办法跑lego_loam吗？ 论文里用了kitti,应该需要特殊处理，作者也没说，就在readme提了一句 ok，那这个开源也开的不是很准确啊 作者提供了他自己采的vlp16的数据集，需要翻墙下载 https://github.com/TixiaoShan/Stevens-VLP16-Dataset ，这个数据没啥用啊，只有激光，我想融合别的传感器还是得找别的数据 那只能找找其他数据集了。。或者自己采 kitti激光这个也太差了吧，太惨了，还得自己修理 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

https://github.com/Mitchell-Lee-93/kitti-lego-loam

**Comment by bryantaoli** [comment]
https://github.com/Mitchell-Lee-93/kitti-lego-loam

**Comment by shikeqin123** [comment]
> https://github.com/Mitchell-Lee-93/kitti-lego-loam
good job

**Comment by ZhangZh3ng** [comment]
> 
请问你都在哪些数据集上验证了该算法
