### ISSUE TITLE
Drift found in localisation of LeGO-LOAM algorithm using rosbag captured from CARLA 

### ISSUE THREAD

**Issue by praveenputhettu** [RobustFieldAutonomyLab/LeGO-LOAM#18]

**Comment by praveenputhettu** [comment]
The Lidar sensor used in capturing the point cloud is VLP-16

**Comment by praveenputhettu** [comment]
Following is the trajectory i got before loop closure
![b4_loopclosure](https://user-images.githubusercontent.com/33420537/45081134-24395700-b114-11e8-82c7-ca5ebedd6089.png)

**Comment by praveenputhettu** [comment]
Following is the trajectory i got after loop closure
![afterloopclosure](https://user-images.githubusercontent.com/33420537/45081466-e557d100-b114-11e8-9ee2-9b7dd5d4dfbb.png)

the loop closure happens only at the end of the path.
The actual path has no angled junctions as in the screen-shots.
i didn't use IMU here.
Can you identify which were the possible reasons of the error.

Thank You.

**Comment by TixiaoShan** [comment]
Hi @praveenputhettu , sorry I don't have experience with using simulated point cloud in LeGO-LOAM. LeGO-LOAM is only designed for real lidar.
