### ISSUE TITLE
why judge degenerate by eigenvalue less than 10 ? 

### ISSUE THREAD

**Issue by chennuo0125-HIT** [RobustFieldAutonomyLab/LeGO-LOAM#180]
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/aa37d0a9553f94ec5c59755cf5fb0a15f84a53f4/LeGO-LOAM/src/featureAssociation.cpp#L1337
I don't know why judge degenerate as above method?

**Comment by AlexSeongJu-sr** [comment]
I have the same question. Why do u judge degeneracy by value 10? does anyone know?
