### ISSUE TITLE
clusters fewer than 30

### ISSUE THREAD

**Issue by saharLeisiazar** [RobustFieldAutonomyLab/LeGO-LOAM#182]
Hi

It is written in your paper "we omit the clusters that have fewer than 30 points." but I could not find any parameter to define 30. Which part of code or which parameter should I change to decrease this number?

**Comment by shikeqin123** [comment]
in “imageProject.cpp” line 442




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"saharLeisiazar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 凌晨4:29
收件人:&nbsp;"RobustFieldAutonomyLab/LeGO-LOAM"<LeGO-LOAM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RobustFieldAutonomyLab/LeGO-LOAM] clusters fewer than 30 (#182)





 
Hi
 
It is written in your paper "we omit the clusters that have fewer than 30 points." but I could not find any parameter to define 30. Which part of code or which parameter should I change to decrease this number?

**Comment by saharLeisiazar** [comment]
Thanks
