### ISSUE TITLE
Static Transform

### ISSUE THREAD

**Issue by nyangshawbin** [RobustFieldAutonomyLab/LeGO-LOAM#184]
Hi, why is there a static transform for camera frame in the default roslaunch file?

![image](https://user-images.githubusercontent.com/55438554/83064666-b4f85900-a094-11ea-89b6-80a5b4dc58ec.png)

Following is the tf_tree of a rosbag i would like to perform LeGO-LOAM on. Can i get some advice on how should the static transform be done?:
![image](https://user-images.githubusercontent.com/55438554/83064735-db1df900-a094-11ea-8fb3-7fcdf4cb6aae.png)

**Comment by Hi-Peng** [comment]
Hi @nyangshawbin, do you have any clue or tips about how to implement the transformation on our own autonomous robots? It would be helpful for anyone. Thank you
