### ISSUE TITLE
rviz completely black when I do roslaunch

### ISSUE THREAD

**Issue by thisisjaskaran** [RobustFieldAutonomyLab/LeGO-LOAM#193]
When I do **roslaunch lego_loam run.launch** rviz open but is completely black and Global Status gives a warning which says **No tf data.  Actual error: Fixed Frame [map] does not exist**. Please help.

This is the terminal result before and after I terminate rviz

![Screenshot from 2020-07-24 05-41-48](https://user-images.githubusercontent.com/52422984/88350347-82a36900-cd70-11ea-84da-cdf06c85aad6.png)

**Comment by thisisjaskaran** [comment]
Don't remember how it worked. Just did.

**Comment by HareshKarnan** [comment]
I had the same issue. It turns that I had set a different machine as the ros master. Fixed it when I set ROS_MASTER_URI as http://localhost:11311
