### ISSUE TITLE
LeGO-LOAM Issue when roslaunch lego-loam

### ISSUE THREAD

**Issue by ihamieh** [RobustFieldAutonomyLab/LeGO-LOAM#197]
hey guys, 
i'm getting the following error message when i roslaunch lego_loam run.launch: 

[mapOptmization-7] process has died [pid 28803, exit code -6, cmd /home/ismail/catkin_ws/devel/lib/lego_loam/mapOptmization __name:=mapOptmization __log:=/home/ismail/.ros/log/c908fc60-e3c9-11ea-9c94-28b2bdb04b77/mapOptmization-7.log].
log file: /home/ismail/.ros/log/c908fc60-e3c9-11ea-9c94-28b2bdb04b77/mapOptmization-7*.log

rviz still open and I can run a bag file but it won't do a map due to that error message! I re-installed everything but problem persisted! let me know if you guys know anything about this error message with Lego-Loam?

**Comment by saiprakash-c** [comment]
Have a look here - #92
Install the correct version of GTSAM as specified in the README.md i.e., 4.0.0-alpha2.
This fixed my issue.
