### ISSUE TITLE
mapOptmization process has died

### ISSUE THREAD

**Issue by MaxandreOgeret** [RobustFieldAutonomyLab/LeGO-LOAM#198]
Hello, I get this error when I start the launchfile :

```
[mapOptmization-7] process has died [pid 6638, exit code 127, cmd /home/xxxxxx/catkin_pkg/devel/lib/lego_loam/mapOptmization __name:=mapOptmization ].

```

gtsam is at the right version : 4.0.0-alpha2.
How to solve this ? thanks

**Comment by MaxandreOgeret** [comment]
Solved when adding /usr/local/lib to ld libraries : 

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```

**Comment by shikeqin123** [comment]
Hi,I have the same problem with you, Can you explain the solution in more detail？ thank you .

**Comment by MaxandreOgeret** [comment]
No problem, the problem was that some libraries were missing. They were installed but not available because not in the LD_LIBRARY_PATH environment variable. So adding `/usr/local/lib` directory to the variable solved my problem.

You just have to run this command before running the launch file : 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`

Make sure gtsam is at the right version also. If it doesnt work, open the launchfile et use rosrun to run each node one by one and see if you get a better error message there

Hope it helps !

**Comment by yinqijun** [comment]
> Hi,I have the same problem with you, Can you explain the solution in more detail？ thank you .

Have you solved this problem? And I find a solution,just try `sudo apt-get install libparmetis-dev`.Look forword for your reply.Thank you!

**Comment by shikeqin123** [comment]
> > Hi,I have the same problem with you, Can you explain the solution in more detail？ thank you .
> 
> Have you solved this problem? And I find a solution,just try `sudo apt-get install libparmetis-dev`.Look forword for your reply.Thank you!

I had solved it, I just install the right bersion of gtsam---**gtsam-4.0.0-alpha2**,   jsut said   at   readme.md
