### ISSUE TITLE
VLP-32C changes

### ISSUE THREAD

**Issue by Kallista** [RobustFieldAutonomyLab/LeGO-LOAM#2]
What would need to be changed to have it work on a 32 layer puck?  const int N_SCAN = 32, i assume in utility.h, but what else? currently it's not working at all

**Comment by TixiaoShan** [comment]
Yeah, it's configured for VLP-16. However, I don't have HDL32. So all the changes below are just my assumptions.
extern const int N_SCAN = 32;
extern const int Horizon_SCAN = 1800;
extern const float ang_res_x = 0.2;
extern const float ang_res_y = 1.33;
extern const float ang_bottom = 30.67;
extern const int groundScanInd = 24;
