### ISSUE TITLE
Change coordinate convention

### ISSUE THREAD

**Issue by 010101101101** [RobustFieldAutonomyLab/LeGO-LOAM#200]
Hi, 

Thank you for the nice algorithm. 

I am feeding to LeGO-LOAM the LiDAR and IMU data both expressed in base-link frame. 

I would expect the odometry to be generated in the XY plane (with the X-forward convention, having the robot moving forward along the X axis) - however, the generated odometry is in the ZY plane (robot moving forward along the Z axis instead of the X axis). 

What is the quick way of handling this to have the odometry generated in the XY plane?

Thank you greatly in advance

**Comment by aprilliuwei** [comment]
hello, do you solve this question?
