### ISSUE TITLE
The cause of featureAssociation modules's output being rotated against the camera frame

### ISSUE THREAD

**Issue by zenified** [RobustFieldAutonomyLab/LeGO-LOAM#201]
Hi, 
I noticed that 2 static transform is published against the camera frame in order to correct for the undesired rotation in the  point clouds published by the featureAssociation module. May I ask the cause of this rotation, and if there are plans to resolve this  so that the static transformations can be removed?

**Comment by rohansingh42** [comment]
I have the same question. I am planning on removing that myself but would appreciate it if anyone can point to the reason as to why it's there in the first place. Am I missing something?
