### ISSUE TITLE
Transformation when advertising and subscribing poses

### ISSUE THREAD

**Issue by qq1962572025** [RobustFieldAutonomyLab/LeGO-LOAM#209]
laserOdometry.header.stamp = cloudHeader.stamp;
        laserOdometry.pose.pose.orientation.x = -geoQuat.y;
        laserOdometry.pose.pose.orientation.y = -geoQuat.z;
        laserOdometry.pose.pose.orientation.z = geoQuat.x;
        laserOdometry.pose.pose.orientation.w = geoQuat.w;
        laserOdometry.pose.pose.position.x = transformSum[3];
        laserOdometry.pose.pose.position.y = transformSum[4];
        laserOdometry.pose.pose.position.z = transformSum[5];
Like the code above，the poses are transformed before advertising and after subscribing.I wonder the transformation is offset. What is the purpose of doing so?

**Comment by shikeqin123** [comment]
maybe just for V-loam. lego-loam is&nbsp;inherited from loam, its author may want to&nbsp;add a camera coordinate system.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RobustFieldAutonomyLab/LeGO-LOAM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 下午4:41
收件人:&nbsp;"RobustFieldAutonomyLab/LeGO-LOAM"<LeGO-LOAM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RobustFieldAutonomyLab/LeGO-LOAM] Transformation when advertising and subscribing poses (#209)





     laserOdometry.header.stamp = cloudHeader.stamp;     laserOdometry.pose.pose.orientation.x = -geoQuat.y;     laserOdometry.pose.pose.orientation.y = -geoQuat.z;     laserOdometry.pose.pose.orientation.z = geoQuat.x;     laserOdometry.pose.pose.orientation.w = geoQuat.w;     laserOdometry.pose.pose.position.x = transformSum[3];     laserOdometry.pose.pose.position.y = transformSum[4];     laserOdometry.pose.pose.position.z = transformSum[5];  
Like the code above，the poses are transformed before advertising and after subscribing.I wonder the transformation is offset. What is the purpose of doing so?
