### ISSUE TITLE
The kitti raw datasets's IMU data for your algorithm

### ISSUE THREAD

**Issue by irobotDavinci** [RobustFieldAutonomyLab/LeGO-LOAM#21]
Hi,I want to use the IMU data in kitti raw datasets to test lego ,just remap '/imu/data' to '/kitti/oxts/imu'
but it goes wrong when turn rotation on z axis.  For example：
![2018-09-12 16-20-35](https://user-images.githubusercontent.com/17939572/45412159-95df4b00-b6a8-11e8-9c49-9e39d2a335bf.png)

And When not use IMU data，it will be ok:

![2018-09-12 16-21-17](https://user-images.githubusercontent.com/17939572/45412158-9546b480-b6a8-11e8-8b18-1c56f0a4947c.png)

The kitti raw datasets coordinate transform between velodyne and imu like this:
![2018-09-12 16-28-08](https://user-images.githubusercontent.com/17939572/45412451-3897c980-b6a9-11e8-8003-c04ae4fbfc00.png)

And in your datasets 2017-06-08-15-49-45_0.bag , the tf is like this:
![2018-09-12 16-30-29](https://user-images.githubusercontent.com/17939572/45412497-5a914c00-b6a9-11e8-8dc9-c9e06fff57d8.png)

Can help me what's wrong?

By the way, is there any doc about featureAssociate.cpp's detail. Thanks

**Comment by irobotDavinci** [comment]
In addition, I use the kitti raw datasets is synced

**Comment by zorosmith** [comment]
![image](https://github.com/zorosmith/material/blob/master/image/legodata.png)

**Comment by zorosmith** [comment]
![image](https://github.com/zorosmith/material/blob/master/image/legodata.png?raw=true)

**Comment by zorosmith** [comment]
In the author's another dataset 2017-06-08-15-51-45_2.bag, the tf is shown in the following picture
![image](https://github.com/zorosmith/material/blob/master/image/legodata.png?raw=true)
This one is different from iroboDavinci's one, which one is correct?

**Comment by narutojxl** [comment]
Hi @irobotDavinci  @TixiaoShan , i also meet this problem. After convert  imu's orientation, acc and angular vel to imu' frame, which has the same origin with original imu frame but align with laser frame,  the problem not solved. I test with kitti_2011_10_03_drive_0027_synced  raw data.
