### ISSUE TITLE
Has someone succeeded in runing LeGO-LOAM with the RS-Bpearl of RoboSense?

### ISSUE THREAD

**Issue by nonlinear1** [RobustFieldAutonomyLab/LeGO-LOAM#216]
I use RS-Bpearl of RoboSense to run LeGO-LOAM, But I failed!  The ROS give me the following message:
![492797550](https://user-images.githubusercontent.com/19766939/103252764-1ed53a00-49b9-11eb-9093-121194ecae91.jpg)

![199030378](https://user-images.githubusercontent.com/19766939/103252806-59d76d80-49b9-11eb-89e5-afcf4ba871fe.jpg)
the parameters of RS-Bpearl are as follows:
lines :32
Horizontal FoV: 360 degree
Vertical FoV :90 degress
Horizontal Resolution: 0.2 degree
Vertical Resolutiion: 2.81 degree
in utility.h
I give the RS-BPearl parameters are as follows:
//RS-BPearl
extern const int N_SCAN = 32;
extern const int Horizon_SCAN = 1800;
extern const float ang_res_x = 0.2;
extern const float ang_res_y = 2.90;//2.81
extern const float ang_bottom = 90;
extern const int groundScanInd = 0;
 Does someone know how to change the LeGO-LOAM and get the right results?
Thank you very much!

**Comment by nonlinear1** [comment]
I have solved this problem

**Comment by arjunskumar** [comment]
@nonlinear1 How did you solve the problem ?

**Comment by Kilam3811** [comment]
Same issue here, may I ask how did you solve it? @nonlinear1  Thanks :)

**Comment by nonlinear1** [comment]
you should filter the nan value of robot sense

在 2022-02-22 22:03:53，Kilam3811 ***@***.***> 写道：


Same issue here, may I ask how did you solve it? @nonlinear1 Thanks :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arjunskumar** [comment]
@nonlinear1  i was able to solve the issue. Thanks

**Comment by Kilam3811** [comment]
@nonlinear1 Thanks for your reply, was able to solve it, thanks 👍

**Comment by lancelonginus** [comment]
I use the same type, how did you solve it？
