### ISSUE TITLE
std::abs(unsigned) - may be a bug, does not compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by ojura** [RobustFieldAutonomyLab/LeGO-LOAM#22]
`segInfo.segmentedCloudColInd` is an `unsigned int32`. In `featureAssociation.cpp`, difference of these `unsigned`s is computed. `std::abs(unsigned)` does not compile on Ubuntu 18.04 due to ambigous overload resolution.

**Comment by TixiaoShan** [comment]
Thanks for the merge! @ojura
