### ISSUE TITLE
the map in z always drift

### ISSUE THREAD

**Issue by PenghangF** [RobustFieldAutonomyLab/LeGO-LOAM#222]
when i build the map , during sometime, the map has big drift in z axis. I don’t know how to solve this problem, I kindly ask for your help 
![image](https://user-images.githubusercontent.com/55130204/111727035-0e8c7700-88a5-11eb-9f49-c97721bf55f0.png)

**Comment by sbhatti915** [comment]
I also experienced this same issue. Were you able to solve it?

**Comment by hanhaoguang** [comment]
I also have this issue. 

The drift is more obvious when walking in a long straight line. 

What is the real reason for the drift?
