### ISSUE TITLE
Own Bag tf_static transformation error

### ISSUE THREAD

**Issue by christophTUM** [RobustFieldAutonomyLab/LeGO-LOAM#230]
Hello,
i am trying to use my own bag with another LiDAR Sensor but right now i am having troubles with the tf transformations.
I wrote a tf_static publisher which publishes from a urdf file, but the Loam needed a /tf topic not a /tf_static topic.

Because of this i remapped the topic to /tf and tried to run the algorithm.
However i get the following error code in rviz: `TF error: [Lookup would require extrapolation at time]`. I dont know how to fix this right now, does anybody know a solution to this?

I saw that there is a file in the src folder which links base_link to camera etc. Do i have to modify this file instead?
```
Transform
For frame [base_link]: No transform to fixed frame [velodyne]. 
TF error: [Lookup would require extrapolation at time 1624356891.904192686, 
but only time 1624356891.904193640 is in the buffe, when looking up transform
from frame [base_link] to frame [velodyne]]
```

**Comment by ghost** [comment]
The error you're getting implies that the time stamp is in the future compared to the latest tf. You don't usually have to remap the transform topic but I haven't used this repo yet. Is your static transform publisher publishing fast enough?
