### ISSUE TITLE
PointXYZ instead of PointXYZIR

### ISSUE THREAD

**Issue by christophTUM** [RobustFieldAutonomyLab/LeGO-LOAM#231]
Hello,
is there a way to use a LiDAR-Sensor with a PointCloud that only has xyz-Point Information?
Or is the minimum requirement xyz, ring, intensity?

Thanks.

**Comment by andres-ss25** [comment]
Hi, @christophTUM  

According to the LOAM algorithm, this format is required. This other project may help you https://github.com/HViktorTsoi/rs_to_velodyne
