### ISSUE TITLE
Where can I find the pcd file of the map created?

### ISSUE THREAD

**Issue by konnoeric** [RobustFieldAutonomyLab/LeGO-LOAM#233]
#229 According to this issue, I am using [this](https://github.com/koide3/LeGO-LOAM-BOR) and tried but cannot find the map. Where is it? It says that the dumped mapping result is at `/tmp/dump` but I don't see any pcd files in it. Is there any code modification needed?

**Comment by konnoeric** [comment]
I found a way to save map in pcd. Case closed

**Comment by Bera97** [comment]
Could you please share how you managed to save the map?

**Comment by surbhi-lab** [comment]
could you please explain how did you do this? and how to know that which frames are exactly being used for the processing?
