### ISSUE TITLE
Loop closure not working 

### ISSUE THREAD

**Issue by konnoeric** [RobustFieldAutonomyLab/LeGO-LOAM#234]
According to the result shown in the photo below, the loop closure is not working. What kind of parameter in the code should I modify?
![IMG_0861](https://user-images.githubusercontent.com/74105724/126145187-ed9a0601-c4e5-49ba-8fe7-c357f8329c67.jpg)

**Comment by BeomBeom2** [comment]
Hello, I'm sorry for asking a question that has nothing to do with this question. I'm asking because I can't find an answer anywhere. I want to visualize the point cloud like the picture above, but my Rviz only shows the progress path. I want to loam by executing the bag file, but the point cloud does not come out, only the progress trajectory. Do you have any special settings?

![image](https://user-images.githubusercontent.com/62642155/126903443-52d2c79f-6d87-4524-884d-312aaa240bb4.png)
`As an additional question, if I change the fixed frame to aft_mapped, an error appears in Surface features, Edge features as shown below. There was an answer to change the time zone, so my current location is Korea, but I changed the time zone to UTC, but the result was the same.`

![image](https://user-images.githubusercontent.com/62642155/126903461-17d91d52-ae5b-445f-94d3-a4250212b176.png)

**Comment by konnoeric** [comment]
Sorry for being late. I don't quite understand what is the problem. Are you using velodyne VLP-16 ? Because this requires velodyne pointclouds. I will show you my screen on Rviz. 
![Screenshot from 2021-07-28 13-35-47](https://user-images.githubusercontent.com/74105724/127264749-33073473-a39a-4a39-9aa3-a25b5146863f.png)

After launched the program, I just published the velodyne's point cloud and did nothing. I did not touch any settings nor buttons of Rviz.

**Comment by BeomBeom2** [comment]
Thank you so much for your reply.
First of all, the above picture was executed in the order shown on the github page without any setting as a Bag file.
Using a fixed frame as a map the path looks good, but the point cloud is not visualized as shown above.

Actually I want to do Lego-Loam with real lidar sensor. The lidar sensor I am using is the VLP-32C model. I changed the parameters of utility.h as shown on the homepage. The model doesn't seem to be causing the error. Both the result of visualization with the actual lidar sensor and the visualization with a Bag file show the same error as in the picture above. I get an error saying For frame [/camera]: no Transform to fixed frame [aft_mapped] Blah blah. When I searched the error contents, there was a recommendation to update the time on the desktop, so I tried it, but the result was the same. Please let me know if there is a way to fix this error or if there is something I missed.

Additionally, I am testing in a virtual machine environment. IMU sensor and VLP sensor are connected to the desktop and are in use.

**Comment by konnoeric** [comment]
How about using my bag file? This is VLP-19 of velodyne. If it works with this, then I think that your configuration for your VLP-32C is not working.

[bag file](https://drive.google.com/file/d/1xdVmNby_T7DaEz6hXNJL2ZPHqpQyN8v-/view?usp=sharing)

**Comment by BeomBeom2** [comment]
Thanks for providing the file. I will try to it
An access request is required to download the file. 
would you please allow it??

**Comment by konnoeric** [comment]
Sorry I did not notice that. I added you so you may see itt now.

**Comment by BeomBeom2** [comment]
Hello. Thanks again for your kind reply. I ran it as a bag, but still the point cloud was not visible in my Rviz. This seems to be my problem. So, I built the same on the virtual machine later and ran it again. Then I found out that it became a visualization. However, I tried Lego_loam to get the value from the actual lidar sensor, but an error like velodyne passed to bla bla as below occurred. Do you have any knowledge or advice you can give?

![image](https://user-images.githubusercontent.com/62642155/127779305-c351192b-c673-4284-aa77-0d5c06d73627.png)

**Comment by konnoeric** [comment]
Sorry I do not have any knowledges to deal with this issue. I don't know.

**Comment by BeomBeom2** [comment]
i See. thanks for the reply though

**Comment by BeomBeom2** [comment]
Hello, I am able to visualize by setting detailed settings in the visualization Rviz tool. So visualization is possible with the VLP32C model. By the way, are you using an IMU sensor? I'm using an IMU, and the point visualization is not connected like a line but is sloppy. Just in case you didn't know, it didn't change even after removing the IMU sensor. Can you tell me the schematic of the robot or the sensor you are using?


What is well expressed like the line below is the raw point cloud received from Velodyne.

![image](https://user-images.githubusercontent.com/62642155/128194994-59af0ad7-e8ab-4b4c-a700-921857c7fd4e.png)


The points below are the point cloud received using lego-loam.

![image](https://user-images.githubusercontent.com/62642155/128196072-c4ffba30-7492-4c18-abfa-d11521d29f9e.png)

**Comment by konnoeric** [comment]
Is this the screenshot of the map created? Im not using robot I just mounted VLP-16 on a handcart and pushed by hand. If I hold the sensor by hand, the result will be horrible since this algorithm is vulnerable to Z-axis drift. I didnt use IMU by the way.

**Comment by BeomBeom2** [comment]
Oh that's right, it seems I'm really vulnerable to the z-axis from testing. However, in the bag file you sent, a large amount of the point cloud is visualized at a time, but when I tried, only a very small amount is visualized little by little. also When checking the bag file you sent me, how can the point cloud initially express the right amount of points clearly? 
I will upload the file for your reference.
[My bag file](https://drive.google.com/file/d/1Y8iQgLJEJS85lwh5VRwNEdvPrxtnY8__/view?usp=sharing)

**Comment by konnoeric** [comment]
Okay, I will take a look by this weekend.

**Comment by BeomBeom2** [comment]
Because you were, I can learn more. Thank you again once :)  :+1:

**Comment by konnoeric** [comment]
Hi, these are the results from your bag file with different angles. 

![Screenshot from 2021-08-22 18-33-42](https://user-images.githubusercontent.com/74105724/130350218-85c63f08-50fb-4919-ab74-f5d7b3a240c4.png)
![Screenshot from 2021-08-22 18-33-13](https://user-images.githubusercontent.com/74105724/130350216-44d84f03-443c-498f-95f5-b54443a35e8b.png)

![Screenshot from 2021-08-22 18-32-42](https://user-images.githubusercontent.com/74105724/130350210-055c8b5a-1860-45be-b619-be88f58ca713.png)
![Screenshot from 2021-08-22 18-32-57](https://user-images.githubusercontent.com/74105724/130350213-6b897af4-3444-493a-a96f-e132cd0da349.png)

**Comment by konnoeric** [comment]
Actually I modified some parameters for better loop closure in the file below. I think the result is different from yours  because I modified this file. Fell free to try this to have the same settings with me and don't forget to rename the extension as .h, not .txt. I did this because I could not upload this file with the name utilitu.h so I changed it to utility.txt. This file is in the path as you can see in the screenshot.
![Screenshot from 2021-08-22 18-41-21](https://user-images.githubusercontent.com/74105724/130350372-8d26380f-ca6b-4789-b522-0248a61f230a.png)


[utility.txt](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/files/7026992/utility.txt)

**Comment by BeomBeom2** [comment]
Oh thank you for the detailed photo. I have one question, When I made the ros bag file, I recorded the bag file after fixing sensors location.
but visualization is not fixed the location. is it my own error??

```
For reference, I am using the VLP32C version. So I am using the following settings in utility.h.
but i think, it seem that VLP32 version is not affect the location itself.

extern const int N_SCAN = 32;
extern const int Horizon_SCAN = 1800;
extern const float ang_res_x = 0.2;
extern const float ang_res_y = 40.0/float(N_SCAN-1);
extern const float ang_bottom = 25.0;
extern const int groundScanInd = 20;
```

**Comment by BeomBeom2** [comment]
oh my jesus, I found why the pointcloud is arbitrary. I think beacuse my room is so small and sealed structure, when I tried to visualization. returned pointcoud is so many that the Lidar sensor wouldn't accept all PCL and then misleaded.

By the way, Did you find a way to make the loopcloser work??

**Comment by GoldenBoylife** [comment]
> [konnoeric](/konnoeric)

I have same issue. did you solve the loop closing? 
In the large scale map (staven university bag file), I found loop closing not working. 
it has   z drift.
![image](https://user-images.githubusercontent.com/81784631/224918959-cebeaa74-e082-463e-b7be-7727a61d6d9d.png)
<total map: bird eye view>
![image](https://user-images.githubusercontent.com/81784631/224918915-9550fbbb-4cfb-42a4-999e-b2f5db7d6bb4.png)
<loop closing not working >

**Comment by ej-sys1** [comment]
> Actually I modified some parameters for better loop closure in the file below. I think the result is different from yours because I modified this file. Fell free to try this to have the same settings with me and don't forget to rename the extension as .h, not .txt. I did this because I could not upload this file with the name utilitu.h so I changed it to utility.txt. This file is in the path as you can see in the screenshot. ![Screenshot from 2021-08-22 18-41-21](https://user-images.githubusercontent.com/74105724/130350372-8d26380f-ca6b-4789-b522-0248a61f230a.png)
> 
> [utility.txt](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/files/7026992/utility.txt)

Hello, I'm experiencing the same issue. I tried to download the utility.h file, but it says it's expired, and it won't download it. Can I get the file shared again?
