### ISSUE TITLE
 bag file does not appear in point cloud in Rviz

### ISSUE THREAD

**Issue by BeomBeom2** [RobustFieldAutonomyLab/LeGO-LOAM#236]
Hello,  I want to loam by executing the bag file, but the point cloud does not come out, only the progress trajectory. Do you have any special settings?

![image](https://user-images.githubusercontent.com/62642155/126903443-52d2c79f-6d87-4524-884d-312aaa240bb4.png)
`As an additional question, if I change the fixed frame to aft_mapped, an error appears in Surface features, Edge features as shown below. There was an answer to change the time zone, so my current location is Korea, but I changed the time zone to UTC, but the result was the same.`

![image](https://user-images.githubusercontent.com/62642155/126903461-17d91d52-ae5b-445f-94d3-a4250212b176.png)

**Comment by qqq428** [comment]
Me too,do you find solution now?
