### ISSUE TITLE
全局地图显示问题

### ISSUE THREAD

**Issue by FiammaDong** [RobustFieldAutonomyLab/LeGO-LOAM#238]
我是用自己的数据包运行的LeGO-LOAM程序，数据包小的话，在Rviz中能显示所有建好的图，没有问题；如果数据包特别大的话，能看到最新的地图建立，而最早时刻建立的地图开始逐渐消失，通过修改utility.h文件中的globalMapVisualizationSearchRadius也还是一样的结果哦，对问题并没有改善。
请问，这种情况要怎么解决呢？

**Comment by yoyoyin0902** [comment]
我是用rosbag -o 存取所有topic數據，後來再將他轉成pcd檔，最後一禎的pcd檔就是完整的地圖了
