### ISSUE TITLE
lego loam 加入IMU發生嚴重飄移問題

### ISSUE THREAD

**Issue by yoyoyin0902** [RobustFieldAutonomyLab/LeGO-LOAM#239]
問題如圖片所示，不與imu連接時 可以穩定建立地圖，但當我加入imu數據後會發生嚴重飄移問題，但可以確定imu送入的值是對的，有人也有類似問題嗎？想問大家如何解決？ 
![first](https://user-images.githubusercontent.com/10761268/130086305-a662585a-e580-4699-a81e-88a5d2f0026b.png)
這是未加入imu的狀態
![end2](https://user-images.githubusercontent.com/10761268/130086479-f885bf4d-bcf3-42c2-b32f-11550996cd6c.png)
加入過後就開始飄移

**Comment by 1499008110** [comment]
您好，我也碰到了同样的问题，您解决了吗？
