### ISSUE TITLE
Problems with VLP-16 dataset w/ IMU

### ISSUE THREAD

**Issue by ojura** [RobustFieldAutonomyLab/LeGO-LOAM#24]
Hi! Would you have a moment to take a look at the dataset provided here?
https://ferhr-my.sharepoint.com/:f:/g/personal/jorsulic_fer_hr/EvwbIJ1tVipLqAJi1ECinDcBLLwKVF0Vki1m4zQ6ye0Jwg?e=TqqWCu

To run Lego-LOAM with the dataset:
```
rosrun imu_filter_madgwick imu_filter_node /imu/data_raw:=imu _publish_tf:=false _use_mag:=false _gain:=0.005
roslaunch lego_loam run.launch
rosbag play processed_type1_traderjoes.bag  points2_1_VLP16:=/velodyne_points --clock
```

The trajectory sometimes looks okay piecewise, but often has jerky moments. Also, in the second part of `processed_type1_traderjoes.bag`, the trajectory goes crazy, up in the air, with an arbitrary pitch and roll - it looks like the gravity measured by the IMU is ignored. As far as I can tell, the IMU is well aligned to the lidar (~< 0.5 degrees). Do you maybe know what could be the cause?

(You may have to install the Madgwick filter with `sudo apt install ros-melodic-imu-filter-madgwick`.)

Also: the frequency is 20 Hz, which means the angular resolution is 0.4 degrees. However, If I tried adjusting for this (the angular resolution), I would get a crash.

**Comment by ksk0050** [comment]
Check 'extrinsic parameters' between Lidar and IMU.

**Comment by ojura** [comment]
Hi @TixiaoShan, is there a chance you could take a look?
