### ISSUE TITLE
Setting up tf for LeGO-LOAM using VLP-16

### ISSUE THREAD

**Issue by chobabo** [RobustFieldAutonomyLab/LeGO-LOAM#26]
Hi, all,

I am trying to get my Velodyne VLP-16 node(topic: velodyne_points) to work with LeGO-LOAM. I can compile the package and play sample bag files. I also have installed velodyne vlp16 and the lidar seems working properly. However, when I roslaunch velodyne node and LeGO-LOAM, I just can't get it right. My command lines are as follows:

$roscore
$roslaunch velodyne_pointcloud VLP16_points.launch
$roslaunch lego_loam run.launch

How to set up tf for LeGO-LOAM using VLP-16?THANKS A LOT.

**Comment by w4rlock999** [comment]
@chobabo I haven't try it yet on real time, but i have a bag file using of my own VLP16 and I could only run the lego-loam using my bag with:

$rosbag play the_name_of_the_bagfile.bag --clock --topic /velodyne_points

where the regular

$rosbag play the_name_of_the_bagfile.bag 

doesn't work, i dont know why

**Comment by gkharish** [comment]
@chobabo , Have you changed the parameter /use_sim_time to false in run.launch? 
In order to make lego_loam work with the real velodyne, you must change the parameter /use_sim_time to false.
