### ISSUE TITLE
terminate called after throwing an instance of 'pcl::IOException' what(): : [pcl::PCDWriter::writeBinary] Input point cloud has no data!

### ISSUE THREAD

**Issue by hyunsehyun** [RobustFieldAutonomyLab/LeGO-LOAM#275]
this exception keep occurs when make a map (ctrl c). how can i fix this error?
An exception has occurred and the final map is not saved.
![image](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/assets/99864704/125c7422-7b3e-4f55-98e0-8317363dc6a6)

**Comment by hyunsehyun** [comment]
i solved this issue. i changed code mapOptmization.cpp. in line 755, 756, 757, 783(map saving part), change like this pcl::io::savePCDFileASCII("/tmp/finalCloud.pcd", *globalMapCloud);.
If you change the path of the pcd validly, the exception will be resolved

**Comment by DeepDuke** [comment]
It seems `globalMapCloud` may be empty. I save other pcds successfully after commenting this line like :
```
// pcl::io::savePCDFileASCII("/tmp/finalCloud.pcd", *globalMapCloud);.
```

**Comment by TheSeanParker** [comment]
that is my answers 
may be help you
https://zhuanlan.zhihu.com/p/709189056

**Comment by hyunsehyun** [comment]
Thank you guys!
