### ISSUE TITLE
cloud_msgs/cloud_info.h: No such file or directory

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [RobustFieldAutonomyLab/LeGO-LOAM#28]
Hi,
I am using ROS Kinect and Ubuntu 16.04. I compile this package using catkin_make and I am obtaining the following error:

> /LeGO-LOAM/LeGO-LOAM/include/utility.h:11:35: fatal error: cloud_msgs/cloud_info.h: No such file or directory
> compilation terminated.
> 
Anybody with the same issue?

**Comment by BrunoEduardoCSantos** [comment]
You have to generate a header file from cloud_info.msg

**Comment by aaravrav142** [comment]
How exactly did you solve this? I am having a similar issue

Thanks

**Comment by BrunoEduardoCSantos** [comment]
catkin_make -j1

**Comment by Summer-Qing** [comment]
catkin_make -DCATKIN_WHITELIST_PACKAGES="cloud_msgs"
