### ISSUE TITLE
How do I test LeGO-LOAM with rosbag

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [RobustFieldAutonomyLab/LeGO-LOAM#29]
Hi ,
I tried to use LeGO-LOAM with my rosbag with Velodyne-16 data, but I cant visualize it on rviz neither the topics are being published.
Any clue about this?
Thanks,
Bruno

**Comment by Yeah2333** [comment]
i have same problem。i use my rosbag with Vlp-16 without imu data。but i can't see point in rviz，and there are some problem about base_link in rviz，How did you solve this problem?

**Comment by andre-nguyen** [comment]
First, try to make it work with the official bags, then check if all your topics are connected to the nodes and then check if your TF static transforms are correct.

**Comment by BrunoEduardoCSantos** [comment]
You just to run the command with filter topic to "/velodyne_points" as mentioned in README

**Comment by BrunoEduardoCSantos** [comment]
and activate the sim_time to true in launch file

**Comment by Yeah2333** [comment]
thank you very much.i have slove the problem. must use readme command to play rosbag through without imu data .but i have another problem./laser_cloud_surround previous points disappeared . Do you have the same problem？

**Comment by BrunoEduardoCSantos** [comment]
Yes. It doesnt display the all global map. I don't know how to solve it.

**Comment by Yeah2333** [comment]
it seems that previous points had been delete?i think the reason is reduce memory usage?but their video on YouTube doesn’t delete previous points.

**Comment by Yeah2333** [comment]
#37 there is how to solve this problem. you should adjust LeGO-LOAM/include/utility.h row 91 extern const float globalMapVisualizationSearchRadius @BrunoEduardoCSantos

**Comment by BrunoEduardoCSantos** [comment]
Thanks a lot @Yeah2333 .
