### ISSUE TITLE
catkin_make error on ubuntu 16.04

### ISSUE THREAD

**Issue by ytgcljj** [RobustFieldAutonomyLab/LeGO-LOAM#31]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
examples/CMakeFiles/Pose2SLAMExample_graph.dir/build.make:62: recipe for target 'examples/CMakeFiles/Pose2SLAMExample_graph.dir/Pose2SLAMExample_graph.cpp.o' failed
make[2]: *** [examples/CMakeFiles/Pose2SLAMExample_graph.dir/Pose2SLAMExample_graph.cpp.o] Error 4
CMakeFiles/Makefile2:14021: recipe for target 'examples/CMakeFiles/Pose2SLAMExample_graph.dir/all' failed
make[1]: *** [examples/CMakeFiles/Pose2SLAMExample_graph.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Linking CXX executable Pose2SLAMwSPCG
[ 64%] Built target Pose2SLAMwSPCG
[ 64%] Linking CXX executable Pose2SLAMExample_lago
[ 64%] Built target Pose2SLAMExample_lago
[ 64%] Linking CXX executable SFMExample_bal_COLAMD_METIS
[ 64%] Built target SFMExample_bal_COLAMD_METIS
[ 66%] Linking CXX executable ImuFactorsExample
[ 66%] Built target ImuFactorsExample
[ 66%] Linking CXX executable SFMExampleExpressions
[ 66%] Built target SFMExampleExpressions
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'gtsam': 
  Command '['/home/firefly/golo_ws/devel_isolated/golo_tools/env.sh', 'make', '-j6', '-l6']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/firefly/golo_ws/build_isolated/gtsam && /home/firefly/golo_ws/devel_isolated/golo_tools/env.sh make -j6 -l6

**Comment by Hlxwk** [comment]
wrong gtsam version
