### ISSUE TITLE
 /laser_cloud_surround previous points disappeared

### ISSUE THREAD

**Issue by Yeah2333** [RobustFieldAutonomyLab/LeGO-LOAM#37]
i use my rosbag with vlp-16.but there are some problem about /laser_cloud_surround . The previous points disappeared . what should i do to avoid this？

**Comment by TixiaoShan** [comment]
@Yeah2333 
Adjust ```globalMapVisualizationSearchRadius``` to a larger value.

**Comment by Yeah2333** [comment]
thank you. i have solve the problem
