### ISSUE TITLE
[run.launch] is neither a launch file in package [lego_loam] nor is [lego_loam] a launch file name The traceback for the exception was written to the log file

### ISSUE THREAD

**Issue by chowkamlee81** [RobustFieldAutonomyLab/LeGO-LOAM#39]
I made belo w commands
cd ~/catkin_ws/src
git clone https://github.com/RobustFieldAutonomyLab/LeGO-LOAM.git
cd ..
catkin_make -j1
In separate terminal i played below 
rosbag play *.bag --clock --topic /velodyne_points /imu/data

But after exceuting
 roslaunch lego_loam run.launch under "catkin_ws" directory, i got error below. Kindly help

[run.launch] is neither a launch file in package [lego_loam] nor is [lego_loam] a launch file name The traceback for the exception was written to the log file

**Comment by andre-nguyen** [comment]
Looks like you didn't source your workspace? 
`source ~/carkin_ws/devel/setup.bash`

I suggest getting familiar with ros through the official tutorials before diving into various packages. Because if you're already stuck at the basics you're going to have a bad time.
