### ISSUE TITLE
Comparing LeGO-LOAM and LOAM using the KITTI Dataset

### ISSUE THREAD

**Issue by claydergc** [RobustFieldAutonomyLab/LeGO-LOAM#41]
Hello,

Maybe the most known LOAM implementation on Github is [laboshinl's version](https://github.com/laboshinl/loam_velodyne), but when testing it with the KITTI Dataset, it doesn't reproduce the original results. I was working with the original code uploaded by J. Zhang [http://docs.ros.org/indigo/api/loam_velodyne/html/files.html](http://docs.ros.org/indigo/api/loam_velodyne/html/files.html) using the raw KITTI Dataset and; even though I get results near the original one, there are some sequences where the original LOAM diverges.

I tried LeGO-LOAM with the sequence 00 of the KITTI Dataset and it returns good results (better than original LOAM's code). I don't know if this occurs because of your algorithm or if the version of LOAM you based your code is the one that can reproduce the original LOAM results.

Since your work is based on LOAM, before starting to implement your code, did you get to reproduce original LOAM results with the KITTI Dataset?.

Thanks for your answer.

**Comment by TixiaoShan** [comment]
@claydergc 
Our focus is for lightweight real-time lidar odometry. As mentioned in Ji Zhang's paper, they run KITTI dataset at 1/10 real-time and yields the best results.
