### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by pangchenglin** [RobustFieldAutonomyLab/LeGO-LOAM#42]

**Comment by Jaccica** [comment]
hi, you must change the parameter in include file like the author said, and change the code in projectPointCloud function. Then you can show the tf tree, you will get correct result if you do what i said.

**Comment by crankler** [comment]
@Jaccica Thank you for yuur reply, but when i try to use this package on my own project, there have some thing wrong with my frame and tf, how can i set these seeting ? Thanks!
![屏幕截图 2019-04-27 00:39:22](https://user-images.githubusercontent.com/31907141/56847192-9dd3be80-690a-11e9-87fd-2a266abdea04.png)
