### ISSUE TITLE
LeGo-LOAM returns a wrong transformation when the car turns sharp at crossroads

### ISSUE THREAD

**Issue by Li-Shang** [RobustFieldAutonomyLab/LeGO-LOAM#43]
I did some modifications to fit the KITTI data. https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/12#issuecomment-414406582 and used LeGo-LOAM on *KITTI sequence 00*. 
when the car goes at crossroads, lego-loam returns wrong transformation as the image shows . ![](https://wx2.sinaimg.cn/mw690/eb7ca78fly1fxp8oa6ljhj20jz0lijuq.jpg)

I changed the iteration times from 25 to 50, but this doesn't work. I am confused about this.

**Comment by mbudris** [comment]
Hi, I have the same behavior at sharp turns also. Tried to alter everything in the .h file, but without any considerable luck.

**Comment by BrunoEduardoCSantos** [comment]
Hi,
Are you using IMU data? That may cause wrong transformations if IMU is not aligned with Velodyne axis.

**Comment by mbudris** [comment]
It is level within a couple degrees.
I tried while being in still position, but a severe drift is observed. Without IMU there is much less drift, but still unable to tune to eliminate.

**Comment by narutojxl** [comment]
Hi @brunoeducsantos i also meet this problem. After convert imu's orientation, acc and angular vel to imu' frame, which has the same origin with original imu frame but align with laser frame, the problem not solved. I test with kitti_2011_10_03_drive_0027_synced raw data.

**Comment by xuwuzhou** [comment]
@narutojxl Hi,have you sovled your problem?I have met the same problem as you
![图片](https://user-images.githubusercontent.com/44218507/71438256-ee1c4e00-272f-11ea-8fc1-a76f67c7c546.png)

**Comment by J-Rojas** [comment]
I've seen the same problem outside of the scope of this project. If you map the path of the vehicle over time with the GPS/IMU pose data to the LiDAR point, there's a misalignment when the vehicle makes heading adjustments. After some time it realigns itself again. Maybe there is some unaccounted time lag in the GPS/IMU data?
