### ISSUE TITLE
HDL-64E

### ISSUE THREAD

**Issue by jiangjianwen** [RobustFieldAutonomyLab/LeGO-LOAM#45]
Hello, I'm using kitti dataset to test your code, I have modified the params as follw:
extern const int N_SCAN = 64;
extern const int Horizon_SCAN = 1800;   //1028~4500
extern const float ang_res_x = 360.0/float(Horizon_SCAN);
extern const float ang_res_y = 28.0/float(N_SCAN-1);
extern const float ang_bottom = 25.0;
extern const int groundScanInd = 60;

are they right? can you provide some advice?

**Comment by TixiaoShan** [comment]
@jiangjianwen 
extern const float ang_res_y = **26.9**/float(N_SCAN-1); might me better.
groundScanInd is the number of scans that covers ground. I think 30 would be a good number. A number that is too large will impact the performance.

Keep in mind that the point cloud in KITTI data set is undistorted. Many points will not be correctly projected when using LeGO-LOAM.

**Comment by SubMishMar** [comment]
@TixiaoShan , How can I use LeGO LOAM with kitti dataset? I don't understand what do you mean when you said above that "Many points will not be correctly projected when using LeGO-LOAM." Can you please explain?

**Comment by claydergc** [comment]
@SubMishMar Here is a short explanation of how the points distortion is managed in laboshinl's LOAM: https://github.com/laboshinl/loam_velodyne/issues/29#issuecomment-349204667

By the way, I tested the LeGO-LOAM with sequence 00 of the raw KITTI Dataset and it returned better results than laboshinl's LOAM.

**Comment by ArisH1B** [comment]
@claydergc hello, I am trying to test the the LeGO-LOAM with sequence 00 of the raw KITTI Dataset, but I get an error :
[imageProjection-5] process has died [pid 23453, exit code -6, cmd /home/aris/catkin_ws/devel/lib/lego_loam/imageProjection __name:=imageProjection __log:=/home/aris/.ros/log/b7525a88-5f50-11e9-aa32-02423cc55f1c/imageProjection-5.log].
log file: /home/aris/.ros/log/b7525a88-5f50-11e9-aa32-02423cc55f1c/imageProjection-5*.log

but when i use sequence 01 to test, this error doesn't happen,
have you ever met with this problem?

and how did you deal with /base_link_to_camera and /camera_init_to_map ?

**Comment by ArisH1B** [comment]
@claydergc Sorry to bother, the error is fixed. And I still want to know that how did you deal with /base_link_to_camera and /camera_init_to_map? My result is not better than laboshinl's LOAM, the map I got is  the same shape as loam's result but it has a different angle which means that it looks like being rotated.

**Comment by narutojxl** [comment]
@jiangjianwen, even though we have adjusted parameters in utility.h, can we directly use KITTI data? On wiki, author says:
> 
    One important thing to keep in mind is that our current implementation for range image projection 
    is only suitable for sensors that have evenly distributed channels. If you want to use our algorithm 
    with Velodyne VLP-32c or HDL-64e, you need to write your own implementation for such 
    projection. If the point cloud is not projected properly, you will lose many points and performance.
For now i have no idea about what we should do for HDL-64e, which is not evenly distributed channels. BTW, have you solved this problem?

**Comment by zhangziz** [comment]
@ArisH1B ,Hi，I have the same question that" [imageProjection-5] process has died ... ...", and how did you deal with ? thank you!
