### ISSUE TITLE
Relocalization in the previously built map? 

### ISSUE THREAD

**Issue by bxc237** [RobustFieldAutonomyLab/LeGO-LOAM#48]
Hi,
If I want to extend this system to have the ability to relocalise the robot in the previously built map, where should I start? I would be most grateful if anyone might be able to give me some advice. THX!!

**Comment by NTUwilliam** [comment]
Hi all

I have the same question with @bxc237 . Can `relocalization `(localize in an existing point cloud map) function be realized in the current version of **LeGO-LOAM**?

If not, can the `relocalization` funtion be added to the future version of **LeGO-LOAM**?
If this can be realized, **LeGO-LOAM** can be much more powerful :)

Anyway, thanks for your great work! @TixiaoShan
