### ISSUE TITLE
Invalid arguments to find_dependency

### ISSUE THREAD

**Issue by zuowanghanguang** [RobustFieldAutonomyLab/LeGO-LOAM#56]
Hello,when I run 'make -j1',I meet the error:
CMake Error at /usr/share/cmake-3.5/Modules/CMakeFindDependencyMacro.cmake:45 (message):
  Invalid arguments to find_dependency
Call Stack (most recent call first):
  /usr/local/lib/cmake/GTSAM/GTSAMConfig.cmake:17 (find_dependency)
  LeGO-LOAM/LeGO-LOAM/CMakeLists.txt:23 (find_package)
Does anyone known  the reason and how to solve it？Thank you!

**Comment by TixiaoShan** [comment]
Have you installed GTSAM that is specified in readme successfully?

**Comment by zuowanghanguang** [comment]
Yes.It is 4.0

**Comment by mjjdick** [comment]
@zuowanghanguang I met the same error and solved by improved my cmake version to 3.10, maybe you can try this solution.

**Comment by zuowanghanguang** [comment]
@mjjdick ok.I will try.Thank you!

**Comment by WAT183** [comment]
I also met this error and I solved this by change "find_dependency" into "find_package" in file GTSAMConfig.cmake

**Comment by JunGooLee** [comment]
I also meet same error. Could you let me know more details?
I couldn't find any ..... T.T

**Comment by OneYouth** [comment]
> I also meet same error. Could you let me know more details?
> I couldn't find any ..... T.T
Both 'mjjdick' and 'WAT183' says are valid. The reason can be reference to 'https://github.com/pabloariasal/modern-cmake-sample/issues/5' , which says "find_dependency() does not support COMPONENTS argument before CMake 3.8.0".
