### ISSUE TITLE
What do these parameters mean and what are their function?

### ISSUE THREAD

**Issue by zorosmith** [RobustFieldAutonomyLab/LeGO-LOAM#57]
In the utility.h
`extern const int imuQueLength = 200`

In the featureAssociation.cpp, 
`bool halfPassed`
`int skipFrameNum`

Any help will be appreciated!
Hope we can have a discussion!

**Comment by TixiaoShan** [comment]
Hi @zorosmith 
'imuQueLength' is the vector length for saving all the IMU data. It can be changed according to your IMU publish rate. 
'skipFrameNum' is the number of skipped scans before running the code.
I am not sure about 'halfPassed'. It was used in the original LOAM.

**Comment by zorosmith** [comment]
Hello @TixiaoShan, thank you for your reply!
If my IMU publishes at 200HZ then imuQueLength=200, right?
