### ISSUE TITLE
How to do Localization only with LeGO-LOAM (Map provided)?

### ISSUE THREAD

**Issue by HappySamuel** [RobustFieldAutonomyLab/LeGO-LOAM#58]
Hi @TixiaoShan 

I successfully generate map with your LeGO-LOAM in gazebo simulation, the map is nice. Here is the pointcloud map.
![Screenshot from 2019-04-06 17-26-23](https://user-images.githubusercontent.com/18137963/55667638-646edc80-5891-11e9-9c5a-6d5dced41b19.png)

But if i want to use LeGO-LOAM to do the localization, is there anything need to be modified to allow localization in a known map? Can you guide me on this?

Best,
Samuel

**Comment by TixiaoShan** [comment]
Hi @HappySamuel 
To localize with LOAM or LeGO-LOAM would need very heavy modifications to all the modules. For example, the feature maps are saved as a vector in mapRegistration.cpp. I would not suggest you do that. However, you may try segMap if you have an existing map.

**Comment by HappySamuel** [comment]
Hi @TixiaoShan 

The segMap you mentioned, is it the one that did by ethz-asl? I will look into that and try it out.  Can I get back to you and consult you if i face any trouble on this segMap? As you have the experience with it.

Best,
Samuel

**Comment by Shelfcol** [comment]
Hi @TixiaoShan，have you tried relocalize the car using LeGO-LOAM with a  known lidar map? Could you give me some advice? thank you
looking forward to your reply.

**Comment by tuencfs** [comment]
@Shelfcol @HappySamuel, I'm trying to do it also, did you find a solution for it?
