### ISSUE TITLE
Something wrong in linking Boost::Timer

### ISSUE THREAD

**Issue by linghusmile** [RobustFieldAutonomyLab/LeGO-LOAM#59]
Hi all, I have meet the following error in catkin_make,I have seen other issue in this project for seeking something may seems like in same situtation but haven't found.  I doubt whether is the version of gtsam not match? But when i make install gtsam, nothing wrong happened. Any reply will be  helpful. thax a lot!
[ 73%] Linking CXX executable /home/chappie/catkin_ws/devel/lib/lego_loam/mapOptmization
/usr/bin/ld: 找不到 -lBoost::timer
collect2: error: ld returned 1 exit status
LeGO-LOAM/LeGO-LOAM/CMakeFiles/mapOptmization.dir/build.make:791: recipe for target '/home/chappie/catkin_ws/devel/lib/lego_loam/mapOptmization' failed
make[2]: *** [/home/chappie/catkin_ws/devel/lib/lego_loam/mapOptmization] Error 1
CMakeFiles/Makefile2:1648: recipe for target 'LeGO-LOAM/LeGO-LOAM/CMakeFiles/mapOptmization.dir/all' failed
make[1]: *** [LeGO-LOAM/LeGO-LOAM/CMakeFiles/mapOptmization.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j1" failed

**Comment by linghusmile** [comment]
I have install sudo apt-get install libboost-all-dev.But seems doesn't works.

**Comment by mbudris** [comment]
It is documented here:
http://wiki.ros.org/catkin/CMakeLists.txt#Boost

**Comment by zorosmith** [comment]
I fixed this error.
Try to re-download the gtsam source code and reinstall it!

**Comment by astronaunt** [comment]
https://github.com/introlab/rtabmap_ros/issues/291

Add " find_package(Boost REQUIRED COMPONENTS timer) " into the CmakeLists.txt.
