### ISSUE TITLE
Why the outlier cloud is added to the global map

### ISSUE THREAD

**Issue by zorosmith** [RobustFieldAutonomyLab/LeGO-LOAM#60]
Hello @TixiaoShan , I am confused why the outlier point cloud is added to the final global map point cloud in _publishGlobalMap_ function in _mapOptmization.cpp_. The code is shown in the following.

for (int i = 0; i < globalMapKeyPosesDS->points.size(); ++i)
{ 
    int thisKeyInd = (int)globalMapKeyPosesDS->points[i].intensity; *globalMapKeyFrames += *transformPointCloud(cornerCloudKeyFrames[thisKeyInd], &cloudKeyPoses6D->points[thisKeyInd]); 
    *globalMapKeyFrames += *transformPointCloud(surfCloudKeyFrames[thisKeyInd], &cloudKeyPoses6D->points[thisKeyInd]);
    *globalMapKeyFrames += *transformPointCloud(outlierCloudKeyFrames[thisKeyInd], &cloudKeyPoses6D->points[thisKeyInd]); 
}

**Comment by TixiaoShan** [comment]
Hi @zorosmith ,

A lot of points in outliers are actually useful points. This is because the segmentation result is not always perfect. Many useful points may not be presented in the segmented points. Adding outlier points back to the map improves the accuracy greatly.
