### ISSUE TITLE
Odom orientation issue

### ISSUE THREAD

**Issue by lchop** [RobustFieldAutonomyLab/LeGO-LOAM#61]
Hello,
First of all thanks for your work. (Edit: added a second issue, concerning odom drift when imu not aligned)
1) First issue. I have an issue concerning the orientation of the odom data published in the topic /aft_mapped_to_init.
The odometry is turned by Pi/2 on the yaw rotation. (See pictures attached)
![Screenshot from 2019-04-18 11-38-16](https://user-images.githubusercontent.com/36415141/56353140-0915e600-61d1-11e9-80a0-19502c1598cd.png)
![Screenshot from 2019-04-18 11-37-58](https://user-images.githubusercontent.com/36415141/56353160-1c28b600-61d1-11e9-920b-84f725dcf1c9.png)

I managed to solved this issue using a "hack", I published a /aft_mapped_to_init_corrected topic with a corrected yaw in the mapOptimization.cpp script:
```
nav_msgs::Odometry odomAftMappedCorrected;
        odomAftMappedCorrected = odomAftMapped;
        geometry_msgs::Quaternion geoQuat2 = tf::createQuaternionMsgFromRollPitchYaw(transformAftMapped[2], -transformAftMapped[0], -transformAftMapped[1] + PI/2);

        odomAftMappedCorrected.pose.pose.orientation.x = -geoQuat2.y;
        odomAftMappedCorrected.pose.pose.orientation.y = -geoQuat2.z;
        odomAftMappedCorrected.pose.pose.orientation.z = geoQuat2.x;
        odomAftMappedCorrected.pose.pose.orientation.w = geoQuat2.w;

        pubOdomAftMappedCorrected.publish(odomAftMappedCorrected);
```
![Screenshot from 2019-04-18 11-48-56](https://user-images.githubusercontent.com/36415141/56353363-7d508980-61d1-11e9-915b-8a55167f0b3d.png)
![Screenshot from 2019-04-18 11-49-09](https://user-images.githubusercontent.com/36415141/56353373-82153d80-61d1-11e9-9ef4-2aef8d313b61.png)

But I am not happy, with this solution, I have searched inside the code to look for a correction and I tried different transforms for map->camera_init with no success. I don't know if It's an error in the computation of the Odom or a config error. Any clue on how to fix this properly, or where does this yaw error come from?

2) Second issue. 
As you mentionned in your ReadMe, if the imu link is not aligned with the laser link the odometry drift, but the localization of the robot in the map is still correct.
First picture, imu is aligned and the odom published by odom (red), the localization (cube) and the ground truth odom (red) are aligned. Second picture, the ground truth odom (white) and the localization (cube) are aligned, but the odom published by lego_loam (red, /aft_mapped_init) is not aligned.
![imu_aligned](https://user-images.githubusercontent.com/36415141/56372883-26ae7400-6200-11e9-8a67-6b939f7621a1.png)
![Screenshot from 2019-04-18 17-30-42](https://user-images.githubusercontent.com/36415141/56373087-8442c080-6200-11e9-8868-58c3448320d6.png)

I know, you alredy noticed this issue, but any clue how to solve this ? Any ideas are welcomed

Thank you in advance !

**Comment by oskarmue** [comment]
Hey, did you find another solution for this problem?
