### ISSUE TITLE
Frame Setting

### ISSUE THREAD

**Issue by crankler** [RobustFieldAutonomyLab/LeGO-LOAM#62]
I try to use LeGO-LOAM on my own projects,but there have something wrong on  the Fixed Frame and Refrence Frame, my baselink is moving when play bag, so if I want to show the baselink is move, how can I set the Frame? Thank you for your share!
![屏幕截图 2019-04-27 00:39:22](https://user-images.githubusercontent.com/31907141/56822857-efd20100-6884-11e9-8098-dc91d5ce5510.png)

![frames](https://user-images.githubusercontent.com/31907141/56822990-48090300-6885-11e9-946d-d0dba07ac372.png)

**Comment by TixiaoShan** [comment]
@crankler 
I am not sure what you mean. Do you want to set `base_link` as the world frame?
