### ISSUE TITLE
Force LeGO-LOAM to perform 2D (tx, ty, yaw) only

### ISSUE THREAD

**Issue by ClementLeBihan** [RobustFieldAutonomyLab/LeGO-LOAM#64]
Hi,

This is not a real "issue", but I would like to know if it's possible to force LeGO-LOAM to only estimate TX, TY and Yaw. 
If we're using LeGO-LOAM on flat area, we don't need (and don't want) to compute Tz, Roll & Pitch.

Do you know if it's possible ?

Best,
Clément

**Comment by TixiaoShan** [comment]
@ClementLeBihan 
I think this is definitely possible. You just need to change all the calculations regarding (tz, roll and pitch) to 0. Unfortunately, there are a lot of them.
