### ISSUE TITLE
Segmentation on range images

### ISSUE THREAD

**Issue by zorosmith** [RobustFieldAutonomyLab/LeGO-LOAM#66]
Hello, @TixiaoShan ! 
I am interested in the segmentation on range images.
In the function _void labelComponents_ in the imageProjection.cpp, almost all steps originate from the ref. **Fast Range Image-Based Segmentation of Sparse 3D Laser Scans for Online Operation**. 
However, in the final step, you do a confusing method to handle the case in which `allPushedIndSize < 30`. More in detail, I don't know what are the means of segmentValidPointNum and segmentValidLineNum.
Could you offer any help?
Thank you!

**Comment by TixiaoShan** [comment]
@zorosmith 
That's just some hand-tuned params. For example, if a segment has number of points less than `segmentValidPointNum`, or segment consists of scan lines less than `segmentValidLineNum`, then I consider it not a segment. It's for noise removal.
