### ISSUE TITLE
LeGO-LOAM for LiDAR not placed horizonatally

### ISSUE THREAD

**Issue by hemangchawla** [RobustFieldAutonomyLab/LeGO-LOAM#67]
Hello,
I was wondering how could the LeGO-LOAM be used for setups where the LiDAR is not placed horizontally?
Thanks

**Comment by BrunoEduardoCSantos** [comment]
Hey,
You have to change the sensorMountAngle parameter.

**Comment by zorosmith** [comment]
Hello, I am trying to rotate the lidar so as to construct the 3D field for climbing robot. But I have not made any progress until now since both lego-loam and loam-velodyne failed to do this. Do you have any idea?
