### ISSUE TITLE
Imageprojection.cpp and Utility.h file for Ouster(OS_16)

### ISSUE THREAD

**Issue by Ashik19** [RobustFieldAutonomyLab/LeGO-LOAM#70]
Anyone using LeGo-LOAM with OS_16? If so, can you please share the Utility.h and Imageprojection.cpp file ?

**Comment by TixiaoShan** [comment]
Hi @Ashik19 ,

The utility.h file for OS-16 can be found here (https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/master/LeGO-LOAM/include/utility.h).
