### ISSUE TITLE
mapOptimization shutdown unexpectedly with errors and warnings

### ISSUE THREAD

**Issue by HappySamuel** [RobustFieldAutonomyLab/LeGO-LOAM#72]
Hi

I tried with Ouster 1-16 Lidar, I record a rosbag and used it. I comment the vlp-16 configuration and uncomment the os1-16 configuration in utility.h

However when i run both the run.launch and bagfile. I got the following errors.

![Screenshot from 2019-05-31 16-47-02](https://user-images.githubusercontent.com/18137963/58693912-669e7480-83c4-11e9-89b1-5bec54418b7a.png)

And this error eventually lead to the shutdown of mapOptimization node.

![Screenshot from 2019-05-31 16-47-30](https://user-images.githubusercontent.com/18137963/58693948-7d44cb80-83c4-11e9-8392-08c7a12819d4.png)

I have no idea where the errors and warnings come from.
Can you please help me out?

Here i attached the link to the bag file:
https://drive.google.com/open?id=1ysiFH0WhU6JqU-xnwHeLL13Tipy9G0JH

Best Regards,
Samuel

**Comment by TixiaoShan** [comment]
Hi @HappySamuel 

Are you able to run it at all? I have no problem running your bag.
![1](https://user-images.githubusercontent.com/9648219/58755084-860fcd00-84aa-11e9-9139-4e389227963b.png)
![4](https://user-images.githubusercontent.com/9648219/58755085-860fcd00-84aa-11e9-8b53-7a12a32b8522.png)

**Comment by HappySamuel** [comment]
Hi @TixiaoShan 

I tried again, but still the same error. Can you share your configuration for running it? Maybe i missed something? Like launch file, utility.h, or command run on terminal?

Best,
Samuel

**Comment by TixiaoShan** [comment]
@HappySamuel 
I just made a few changes. Take a look at the commits made today.
My command:
`roslaunch lego_loam run.launch`
`rosbag play 2019-05-27-18-38-00.bag --clock --topic /os1_cloud_node/points`

**Comment by TixiaoShan** [comment]
@HappySamuel 
Ah, I think the imu data from Ouster lidar is different from the data from some other mainstream IMUs. I had that problem before. I will take a look at the imu data in detail once I have more time. You can just publish point cloud data for now to use LeGO-LOAM.

**Comment by HappySamuel** [comment]
Hi @TixiaoShan 

I did as what you said, but how come the map i generated is different from yours? Here i attached the map below:
![Screenshot from 2019-06-03 17-08-58](https://user-images.githubusercontent.com/18137963/58790193-73b89f00-8622-11e9-8dce-4f97593053c7.png)


Best,
Samuel

**Comment by TixiaoShan** [comment]
@HappySamuel 
That looks weird. The point cloud map looks ok. The trajectory is completely wrong.

**Comment by HappySamuel** [comment]
Hi @TixiaoShan 

Could it possibly be the mapping parameters that give different result? Maybe mine and yours are different? But i am using your latest update package, however no matter how many times i tried, i always got the same result.

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @TixiaoShan 

I manage to get the same result as yours. It's due to i comment out the VLP-16 parameters in utility.h, but i forgot to uncomment the OS1-16 parameters. After i uncomment them, the result is correct now.

![Screenshot from 2019-06-04 10-54-03](https://user-images.githubusercontent.com/18137963/58847932-33573080-86b7-11e9-8c8d-190418335f9f.png)

Appreciate for your help and patient that you gave. Thank you very much.
 
Best, 
Samuel
