### ISSUE TITLE
Uploading a pre-built map in the rviz

### ISSUE THREAD

**Issue by Ashik19** [RobustFieldAutonomyLab/LeGO-LOAM#73]
Is it possible to upload a pre-built map in the rviz ? If so, can anyone please tell me how to do it. I have this map and I want to upload it inside the rviz. 

Thanks 
Ashik

![USU_16_12414_24389](https://user-images.githubusercontent.com/49127638/58744924-6f179f00-8406-11e9-8b4a-e254596b00b4.png)

**Comment by TixiaoShan** [comment]
This post should give you some hints to display image in Rviz.

https://answers.ros.org/question/218502/rviz-display-image-in-3d-scene/
