### ISSUE TITLE
Invalid argument "/camera_init" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:

### ISSUE THREAD

**Issue by HappySamuel** [RobustFieldAutonomyLab/LeGO-LOAM#79]
Hi @TixiaoShan 

I tried to use pointcloud_to_pcd function from pcl_ros package to save the map. But I found that there might be some issue for using "/" on declaration of the frame id, especially in tf2. The error is attached as below:

![Screenshot from 2019-06-04 14-03-08](https://user-images.githubusercontent.com/18137963/58855029-80e09700-86d1-11e9-8a21-77f4a7794ebc.png)

However, if the "/" is removed from declaration of the frame id, won't have problem like this anymore.

Best Regards,
Samuel

**Comment by TixiaoShan** [comment]
@HappySamuel 
Thanks for point this out!

**Comment by zorosmith** [comment]
When I save the map, I did not meet this error.

**Comment by HappySamuel** [comment]
Hi @zorosmith 

With the new map saving function that TixiaoShan added in, this error is gone.

Best,
Samuel
