### ISSUE TITLE
Error in Rosbag play

### ISSUE THREAD

**Issue by Ashik19** [RobustFieldAutonomyLab/LeGO-LOAM#80]
Hi @TixiaoShan ,

When I am trying to play the pointcloud2 topic in the legloam of a pre-recorded bag file with "map" as the fixed frame I am getting an error.

"Message_Removed because its too old(frame=/os1_lidar) stamp=[587.990

and a warning under the TF for aft_map

![image](https://user-images.githubusercontent.com/49127638/58871586-8b724080-867f-11e9-8db3-bc7e4397c002.png)

The tf tree graph of my bag is here

![image](https://user-images.githubusercontent.com/49127638/59121667-00f73e80-8916-11e9-8128-80afe686c40e.png)

Can you please tell me where I am making mistake ? How can I sync this recorded bag file time with the ros time ?

I have changed my launch file, utility.h, and imageprojection.cpp file to adjust the change for using the LeGO-LOAM for Ouster (OS_16). The herewith attached picture is for my launch file which modified from other users recommendation.
![image](https://user-images.githubusercontent.com/49127638/58871701-c4aab080-867f-11e9-947b-232a8519f19c.png)

I am using the following bag file 

https://drive.google.com/file/d/1I6vGU6vWApiCQNa2sZAgHeUocVNpTGoH/view?fbclid=IwAR2LJV2zzoQIejjdvpolHqwoSJxsaUdi4gYa1s4ebddZQFw_SWDVBzgCq24

Thank you very much for your valuable time.

Thanks

**Comment by Dinatorehanova** [comment]
Hi @TixiaoShan,

I want to share something about my tf tree to clarify my problem. its like when I initially start the lego-loam my tf tree is like as following 

![62049985_2463277757240856_5136022832878190592_n](https://user-images.githubusercontent.com/51459647/59097494-f3709300-88da-11e9-90f6-628ebc628c49.jpg)

But once I run the rqt_tf_tree then it gets changed along with a warning like

![image](https://user-images.githubusercontent.com/51459647/59097595-37fc2e80-88db-11e9-8f5a-f1bb0c38ca47.png)

![61947018_263192034517117_715268095240830976_n](https://user-images.githubusercontent.com/51459647/59097555-1ac76000-88db-11e9-85d0-19ccca701e0f.jpg)

I have not even opened my pointcloud2 topic. I guess I am missing something important.I am using the latest package of lego_loam and made all the required change in the following files (utility.h, imageprojection.cpp, run.launch) to adjust for ouster(os_16).

Thank you very much for your valuable time.

Thanks 

Ashik

**Comment by Ashik19** [comment]
Hi @TixiaoShan,

I want to share something about my tf tree to clarify my problem. its like when I initially start the lego-loam my tf tree is like as following 

![62049985_2463277757240856_5136022832878190592_n](https://user-images.githubusercontent.com/51459647/59097494-f3709300-88da-11e9-90f6-628ebc628c49.jpg)

But once I run the rqt_tf_tree then it gets changed along with a warning like

![image](https://user-images.githubusercontent.com/51459647/59097595-37fc2e80-88db-11e9-8f5a-f1bb0c38ca47.png)

![61947018_263192034517117_715268095240830976_n](https://user-images.githubusercontent.com/51459647/59097555-1ac76000-88db-11e9-85d0-19ccca701e0f.jpg)

I have not even opened my pointcloud2 topic. I guess I am missing something important.I am using the latest package of lego_loam and made all the required change in the following files (utility.h, imageprojection.cpp, run.launch) to adjust for ouster(os_16).

Thank you very much for your valuable time.

Thanks 

Ashik

**Comment by Ashik19** [comment]
I solved this one.The pitfall was I uncomment the cloudheader.stamp=ros::Time::now(); in the image projection.cpp file.By doing uncomment it turns back the timestamp causing it too old to publish the pointcloud topic
