### ISSUE TITLE
TransformToStartIMU，TransformToStart，TransformToEnd meaning?

### ISSUE THREAD

**Issue by narutojxl** [RobustFieldAutonomyLab/LeGO-LOAM#81]
@TixiaoShan Thanks  for your wonderfully work. There are some questions confused me.

1. In adjustDistortion(), we have convert laser points into the first point time stamp velodyne frame by `TransformToStartIMU(&point)`, which use IMU info interpolated every point time stamp velodyne frame state, then convert to the first point time stamp velodyne frame. In other words, we have undistort points caused by robot motion during this frame, right?  
When we find `findCorrespondingCornerFeatures() && findCorrespondingSurfFeatures() `, we according to `transformCur`, which initial value gived by imu in `updateInitialGuess()`,   transform current laser points  to last frame by `TransformToStart()`. 
 In `TransformToStart()`, why `float s = 10 * (pi->intensity - int(pi->intensity));` not `s =1`?  Because i think we already have undistorted points, for now we just need to transform points to last frame start frame,  so should `s=1`.
 When doing transform, R is composed of transformCur[0,1,2], t is transformCur[3,4,5]. let ` R = Ry(yaw) * Rx(pitch) * Rz(roll)`,  Why not Ry(-yaw) first, then  Rx(-pitch), and last Rz(-roll)?  The transform order in code is Rz(-roll) first, then Rx(-pitch), and last Ry(-yaw).

2. When we end calculating laser odometry ,then publish `publishCloudsLast()`,  why we again transform current  less surf points and current less corner points  by `TransformToEnd()`?  If we did not call this `TransformToEnd()`,  directly send  current  less surf points and current less corner points to `kdtreeCornerLast && kdtreeSurfLast` for next laser points use. If so, when next tk laser points come in,  we calculated `transformCur[]` is from  tk_start point  to tk-1_start point transform, it also make sense, right?

3. BTW, in `updateInitialGuess()`, why we assign `transformCur[3] -= imuVeloFromStartX * scanPeriod; `, why not  `transformCur[3] = -imuVeloFromStartX * scanPeriod;`?

**Comment by chenxianbo** [comment]
@TixiaoShan 　in updateInitialGuess(), why we assign transformCur[3] -= imuVeloFromStartX * scanPeriod; , why not transformCur[3] = -imuVeloFromStartX * scanPeriod;?
