### ISSUE TITLE
How to use lego-loam created 3d map to navigation?

### ISSUE THREAD

**Issue by narutojxl** [RobustFieldAutonomyLab/LeGO-LOAM#82]
Hi, @TixiaoShan , after we created 3d point cloud map(inlcuding all keyframes and coressponding point cloud),  how to use it in later navigation, we should save it in which format to use to locate robot in built 3D point map, some recommended papers, website about this are very much appreciated!

**Comment by tuencfs** [comment]
HI, @narutojx, l  did you find the way to resolve it? how can we use 3D point cloud map for navigation later?
