### ISSUE TITLE
How to save a map generated from LeGO-LOAM

### ISSUE THREAD

**Issue by Dinatorehanova** [RobustFieldAutonomyLab/LeGO-LOAM#84]
Hi,

I have got a map from my bag file using the pointcloud2 topic .Can anyone please tell me how i can save it/which format to use it for further analysis.

Thanks
Dina

**Comment by Scrumantic** [comment]
Hi Dina.

One simple way of doing this is by using the function savePCDFileASCII as documented in http://pointclouds.org/documentation/tutorials/writing_pcd.php

I'm using this and it works perfectly. I hope it helps, I plan to document this with more detail and further steps in a future contribution. 

Best Regards,
Ricardo

**Comment by Ashik19** [comment]
Hi, 

Thank you very much for your kind reference

**Comment by Dinatorehanova** [comment]
Hi,

Thank you very much for referring this resource.
