### ISSUE TITLE
‘fileDirectory’ was not declared 

### ISSUE THREAD

**Issue by Abramenko** [RobustFieldAutonomyLab/LeGO-LOAM#87]
The variable "fileDirectory"  was not declared in file LeGO-LOAM/src/mapOptmization.cpp:705. So, there is a error when build with "catkin_make -j1"
Need to add some declaration to LeGO-LOAM/LeGO-LOAM/include/utility.h

**Comment by TixiaoShan** [comment]
@Abramenko 
Bug fixed.
