### ISSUE TITLE
Imu data source

### ISSUE THREAD

**Issue by ghost** [RobustFieldAutonomyLab/LeGO-LOAM#90]
I would like to know whether I want to use a separate sensor as the IMU data source while applying LeGO-LOAM for Ouster LiDAR(OS-16). How can I set up the IMU source ? Shall I have to just simply change the imu topic in the utility.h file ?

extern const string imuTopic = "/imu/data";

Can anyone please tell me how to add external IMU source from a separate sensor in the LeGO-LOAM?

Thanks

**Comment by TixiaoShan** [comment]
You can change the imu topic to your sensor topic. You can find more discussions about imu on loam_velodyne.

laboshinl/loam_velodyne#82
