### ISSUE TITLE
Mapping Issue with bag file

### ISSUE THREAD

**Issue by Ashik19** [RobustFieldAutonomyLab/LeGO-LOAM#91]
Hi @TixiaoShan ,

Can you please have a look at the herewith attached bag file ? I am not getting any trajectory data and the map it is generating is very odd compared to the ground.I collected this ata using ouster lidar mounted on a car.I have made change in the utility.h file in order to adjust the relative change but still do not know why I am getting this error.

https://l.facebook.com/l.php?u=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1BvZiqFwOI9FRk23IK5fU5Oxav6dzWe2y%2Fview%3Fusp%3Dsharing%26fbclid%3DIwAR00pFBehju7tip2cu536zzG-woLD7Q3FYmRdfMG0Ohfb-3FgjU3XKEDLeI&h=AT3Ef6f0J9lUOFcp7PsoXu-mXKNlJhwfRJ_GORz_ENLc_4NkO8TNdiGiNZIQtpHATgzm2tMol3qvuBj6ZVb8J0NfzvU9YeHDO3DPirIKK4NAJOuXDxNx0cjOk84p-w

![image](https://user-images.githubusercontent.com/52055757/59892860-177eaa80-9398-11e9-9c84-988f1f07f8ce.png)

my launch file is as following
<launch>
    
    
    <param name="/use_sim_time" value="true" />

    
    <node pkg="rviz" type="rviz" name="rviz" args="-d $(find lego_loam)/launch/test.rviz" />

    
    <node pkg="tf2_ros" type="static_transform_publisher" name="camera_init_to_map"  args="0 0 0 1.570795   0        1.570795 map    camera_init " />
    <node pkg="tf2_ros" type="static_transform_publisher" name="base_link_to_camera" args="0 0 0 -1.570795 -1.570795 0        camera base_link   " />
   <node pkg="tf2_ros" type="static_transform_publisher" name="base_link_to_os1sensor" args="0 0 0 0 0 0       base_link os1_sensor   " />

        
    <node pkg="lego_loam" type="imageProjection"    name="imageProjection"    output="screen"/>
    <node pkg="lego_loam" type="featureAssociation" name="featureAssociation" output="screen"/>
    <node pkg="lego_loam" type="mapOptmization"     name="mapOptmization"     output="screen"/>
    <node pkg="lego_loam" type="transformFusion"    name="transformFusion"    output="screen"/>

</launch>

Thank you very much for your valuable time. I will wait for your  valuable feedback.

**Comment by TixiaoShan** [comment]
Hi @Ashik19 
It seems your point cloud data is wrong. The white line in the image represents the horizon. It seems that all your data is offset downwards.

![ouster_detail_pred1](https://user-images.githubusercontent.com/9648219/59968680-90524380-950b-11e9-953c-4a087d3453a1.png)

**Comment by Ashik19** [comment]
Hi, @TixiaoShan ,

Thank you very much for your kind reply.I have also faced this same issue with some of my other bag files like this.I am using an ouster Lidar(OS-16) mounted on a car. Can you recommend something about how to avoid this issue? 
Thanks

**Comment by TixiaoShan** [comment]
Hi @Ashik19 
I can't comment on that. I never used that lidar. Probably it's best to ask the tech support.

**Comment by Ashik19** [comment]
@tixiaoshan, thank you very much for being patient with me. Can you please tell me how did you get the white line indicating the horizon of the point cloud ?

**Comment by Ashik19** [comment]
Hi @ tixiaoshan,

Could it be possible that I have to use a horizontal resolution of 1024 always while using Lego loam in order to resolve this problem. I guess the code in the utility.h looks for a horizontal scan resolution of 1024 while making maps. There are different resolution and scan speed available in ouster like “512x10”, “512x20”,”1024x10”, and “1024x20”. I guess if I wang to use different resolution each time I will have to change the parameter in the utility.h and do the catkin_make? 

Thank you for your valuable time

**Comment by TixiaoShan** [comment]
Yeah, the params in utility.h are set for different sensors with different resolutions. You need to re-compile for each resolution.

**Comment by TixiaoShan** [comment]
> @TixiaoShan, thank you very much for being patient with me. Can you please tell me how did you get the white line indicating the horizon of the point cloud ?

It's just the Grid in Rviz.

**Comment by Ashik19** [comment]
Hi @tixiaoshan,

Thank you very Much for your kind reply. I figured the location of the lidar matters while mounting it on car. Also may I know whether I will have to change the Other parameter like angular resolution  x,y  in the utility.h file since I am using a car to work with LeGO- Loam.

**Comment by TixiaoShan** [comment]
This user's bag has the same issue like yours (point cloud not symmetric relative to the horizon).

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/94
