### ISSUE TITLE
Map optimization process died when launching lego loam

### ISSUE THREAD

**Issue by Dinatorehanova** [RobustFieldAutonomyLab/LeGO-LOAM#92]
Hi @TixiaoShan 

Can you please have a look at the herewith attached picture ?
![image](https://user-images.githubusercontent.com/51459647/59905398-5d049d00-93c3-11e9-9d8c-5563d58f2d9f.png)

How can I resolve this issue ?

Thanks

**Comment by W-Liur** [comment]
Have you solved it? I have the same problem.

**Comment by Ashik19** [comment]
@W-Liur , No, I do not understand why it's coming up. I have tried to clone and do the catkin_make again .But still no success. Please let me know if you come up with any solution.

**Comment by Dinatorehanova** [comment]
@W-Liur , No I have not solved it yet. I have tried to clone and do the catkin_make -j1 again but still with no success.Please, let me know if you have any update on this.

Thanks

**Comment by W-Liur** [comment]
Nor did I succeed.I'm trying the previous version, but it's a bit slow to download.

**Comment by W-Liur** [comment]
I have fixed it.You can reinstall gtsam.Maybe you need this version.https://pan.baidu.com/s/1wVwtAT-Q3uD2WZN9xoiMBg      KEY:i64o

**Comment by TixiaoShan** [comment]
Looks like it's a GTSAM problem. Have you tried the version that is used in README?

**Comment by Dinatorehanova** [comment]
Hi, @TixiaoShan, Thank you very much for your kind reply. I tried to install the mentioned GTSAM and it works.But still there is 

"0x2bf88d0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2557460) ): Attempt to set a screen on a child window."

![image](https://user-images.githubusercontent.com/51459647/59967374-1eb3ce80-94e6-11e9-8023-86b1f72f55d1.png)

Can you please tell me how to address this ? Also I would like to know whether there is any speed issue while using the LeGO-LOAM as it seems id does not provide any map or clear trajectory while using this tool for a high speed car with LiDAR mounted on it.

Thanks

**Comment by TixiaoShan** [comment]
I don't know this new issue. It doesn't look like a LeGO-LOAM issue.
If the car speed is too high, there might be not enough overlaps between two scans, then LOAM will fail.

**Comment by Dinatorehanova** [comment]
Thank you @TixiaoShan .
