### ISSUE TITLE
Load pcd and point cloud matching

### ISSUE THREAD

**Issue by Scrumantic** [RobustFieldAutonomyLab/LeGO-LOAM#93]
Hi everyone!

Has anyone been able to load a point cloud previously saved and match the current view (navigation application)? 
I've been looking mainly to the featureAssociation.cpp and mapOptmization.cpp and trying to make some modifications so it start from a previously saved map. In the end I've not been successful. 
If anyone has some tips I'd appreciate it, otherwise I'll try to use another method for matching the point clouds and then get the transform parameters. It will work but maybe there would be an easier way. Thank you in advance!

**Comment by TixiaoShan** [comment]
This would need very heavy modification to mapOptimization part. You need to save each point cloud that is associated with each pose in the vector. Later you need to load them so you can reuse them.
