### ISSUE TITLE
No trajectory path while recording bag file in (sim time False mode)

### ISSUE THREAD

**Issue by Dinatorehanova** [RobustFieldAutonomyLab/LeGO-LOAM#94]
Hi, @TixiaoShan  I was trying to make an indoor map with sim time false but when I was moving with my lidar unit inside the room it does not provide me any trajectory path.I also tried to again play the bag file in simulation time(true) but still it does not provide any trajectory.Can you please spare some of your valuable time to look into the herewith attached bag file 

https://drive.google.com/file/d/18mdPdLWP-nrtKwTwl6-D9ZCPOx2OD5lv/view?usp=sharing

![image](https://user-images.githubusercontent.com/51459647/59970488-d8319480-9524-11e9-978c-ca69f2e58d9e.png)

Thank you very much for your valuable time.

**Comment by TixiaoShan** [comment]
It seems that you have the same problem like this issue.

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/91

**Comment by Dinatorehanova** [comment]
@Tixiaoshan,thanks for your valuable feedback. I am encountering an error like even when my vehicle is static it seems the legoloam (sim time false) is moving my base_link and creating map with very strange trajectory and generating maps which are very weird compared to my surround. Can you please tell me what can cause this issue ?

Thank you

**Comment by TixiaoShan** [comment]
So I assume you have solved https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/91. That's weird it's still not working.

**Comment by Dinatorehanova** [comment]
Thank you @TixiaoShan . It was my mistake I tried different resolution without configuring the utility.h file

**Comment by ghz009** [comment]
> Thank you @TixiaoShan . It was my mistake I tried different resolution without configuring the utility.h file

Hi @Dinatorehanova ，I met the same problem. Can you tell me how you solved the problem，please.

![2021-05-06 17-03-12 的屏幕截图](https://user-images.githubusercontent.com/82874489/117271933-43707f80-ae8d-11eb-821b-236f6c2e36bd.png)
