### ISSUE TITLE
Map optimization wants topic /odometry/filtered to have datatype/md5sum[sensor_msgs/IMU/] dropping connection

### ISSUE THREAD

**Issue by Ashik19** [RobustFieldAutonomyLab/LeGO-LOAM#96]
![image](https://user-images.githubusercontent.com/52055757/60056769-4b5f1600-969f-11e9-9f28-b12b1e385f03.png)

@TixiaoShan , I am trying to use the robot localization package and use the /odometry/filtered topic generated from the EKF(extended kalman filter node) as the imu topic in the utility.h file.But somehow I am coming up with the given error.Can you please tell me how to address this problem ?

Thank you very much for your valuable time.

Best
Ashik

**Comment by HappySamuel** [comment]
Hi @Ashik19 

From what i know, "odometry/filtered" is originally from Robot Localization Package, and its message type is nav_msgs::Odometry. And what featureAssociation and mapOptimization are requesting sensor_msgs::Imu. So you need to give it IMU topic, instead of odometry topic.

Best,
Samuel

**Comment by chenweng2009** [comment]
Hi @HappySamuel ,

Thank you very much for your kind reply. I have an INS unit which publishes /ins and /imu topic. 

![image](https://user-images.githubusercontent.com/51795019/60072821-e2e25a00-96db-11e9-94e4-1aea946285f9.png)


When I am putting the /ins topic in the utility.h getting the following error


![image](https://user-images.githubusercontent.com/51795019/60072787-c9411280-96db-11e9-937b-59915c0b4682.png)
And when I am putting the /imu topic in the utility.h I am getting this error

![image](https://user-images.githubusercontent.com/51795019/60072757-b6c6d900-96db-11e9-8465-65397557e3de.png)

@TixiaoShan, can you please suggest me how I can address this problem ?

Thank you very much for your valuable time.

**Comment by Ashik19** [comment]
Hi @HappySamuel ,

Thank you very much for your kind reply. I have an INS unit which publishes /ins and /imu topic. 
The /ins is (navigation odometry) while the /imu is the imu.
![image](https://user-images.githubusercontent.com/51795019/60074257-b9c3c880-96df-11e9-8d09-5c5b776c57cf.png)

The data provided by this 2 topics are following
![image](https://user-images.githubusercontent.com/51795019/60074307-d6600080-96df-11e9-8d7d-2a9e859c0419.png)

When I am putting the /imu topic in the utility.h I am getting the following error
![image](https://user-images.githubusercontent.com/51795019/60074364-f5f72900-96df-11e9-941a-f706de48cd07.png)

@TixiaoShan, can you please suggest me how I can address this problem ?

Thank you very much for your valuable time.

**Comment by HappySamuel** [comment]
Hi @Ashik19 

Sorry for the late reply. The imu data stream that LeGO-LOAM package required is the orientation section. However, your /imu data stream is having the orientation all zeros. That's the reason causes the error message.

Best,
Samuel
